import { useState } from "react";
import { readErrorMessage } from "../../../../data/api/read-error-message";
import { useLocalization } from "../../../../localization/LocalizationProvider";
import { Button } from "../../../../ui-kit/components/Button";
import { Card } from "../../../../ui-kit/components/Card";
import { Input } from "../../../../ui-kit/components/Input";
import { EmptyState, Field, PageHeader, SectionHeader, StatusBadge } from "../../../../ui-kit/components/Page";
import { Table } from "../../../../ui-kit/components/Table";
import { ToastNotice } from "../../../../ui-kit/components/ToastNotice";
import { authorPortalRequests, useAdminAuthorRequests, useAuthorPortalMutation, type AuthorRequest } from "./api";

export function AuthorAdministrationPage() { const { t } = useLocalization(); const requests = useAdminAuthorRequests(true); const mutate = useAuthorPortalMutation(authorPortalRequests.reviewRequest); const [notes, setNotes] = useState(""); const [notice, setNotice] = useState<string | null>(null); const act = async (item: AuthorRequest, action: string) => { try { await mutate.mutateAsync({ requestId: item.request_id, action, notes }); setNotice(t("authorPortal.reviewStarted")); } catch (error) { setNotice(readErrorMessage(error)); } }; const actions = (item: AuthorRequest) => <div className="flex flex-wrap gap-2">{item.status === "submitted" && <Button size="sm" onClick={() => void act(item, "start_review")}>{t("authorPortal.startReview")}</Button>}{item.status === "pending_review" && <><Button size="sm" onClick={() => void act(item, "approve")}>{t("authorPortal.approve")}</Button><Button size="sm" variant="outlined" onClick={() => void act(item, "request_changes")}>{t("authorPortal.requestChanges")}</Button><Button size="sm" variant="danger" onClick={() => void act(item, "reject")}>{t("authorPortal.reject")}</Button></>}{item.status === "approved" && <><Button size="sm" variant="outlined" onClick={() => void act(item, "suspend")}>{t("authorPortal.suspend")}</Button><Button size="sm" variant="danger" onClick={() => void act(item, "revoke")}>{t("authorPortal.revoke")}</Button></>}</div>; return <div className="space-y-5"><PageHeader eyebrow={t("nav.platformSettings")} title={t("authorPortal.authorReviews")} description={t("authorPortal.reviewDescription")} />{notice && <ToastNotice message={notice} tone="success" onDismiss={() => setNotice(null)} />}<Card><Field label={t("authorPortal.reviewNotes")}><Input value={notes} onChange={(event) => setNotes(event.target.value)} /></Field></Card><Card className="p-0"><SectionHeader title={t("authorPortal.authorReviews")} />{requests.data?.items.length ? <Table className="rounded-none border-x-0"><tbody>{requests.data.items.map((item) => <tr key={item.request_id}><td>{item.requested_display_name}<div className="text-xs text-hc-muted">{item.contact_email}</div></td><td><StatusBadge>{t(`authorPortal.status.${item.status}`)}</StatusBadge></td><td>{actions(item)}</td></tr>)}</tbody></Table> : <EmptyState>{t("authorPortal.noReviews")}</EmptyState>}</Card></div>; }
