import { useState } from "react";

import { readErrorMessage } from "../../../data/api/read-error-message";
import { useLocalization } from "../../../localization/LocalizationProvider";
import { Button } from "../../../ui-kit/components/Button";
import { Card } from "../../../ui-kit/components/Card";
import { Input } from "../../../ui-kit/components/Input";
import { EmptyState, Field, PageHeader, SectionHeader, StatusBadge } from "../../../ui-kit/components/Page";
import { Select } from "../../../ui-kit/components/Select";
import { Table } from "../../../ui-kit/components/Table";
import { ToastNotice } from "../../../ui-kit/components/ToastNotice";
import { authorPortalRequests, useAuthorOverview, useAuthorPortalMutation, type AuthorMode } from "./api";

export function AuthorOnboardingPage() {
  const { t } = useLocalization(); const overview = useAuthorOverview(); const create = useAuthorPortalMutation(authorPortalRequests.createRequest); const submit = useAuthorPortalMutation(authorPortalRequests.submitRequest);
  const [mode, setMode] = useState<AuthorMode>("talpaversum_hosted"); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [description, setDescription] = useState(""); const [jwks, setJwks] = useState(""); const [issuer, setIssuer] = useState(""); const [terms, setTerms] = useState(false); const [notice, setNotice] = useState<{ message: string; tone: "success" | "danger" } | null>(null);
  const save = async () => { try { await create.mutateAsync({ requested_display_name: name, legal_name: null, contact_email: email, website: null, git_provider_profile: null, description, operating_mode: mode, intended_distribution: "official_catalog", terms_accepted: terms, public_jwks: mode === "trusted_self_hosted" ? JSON.parse(jwks) : null, external_issuer_url: mode === "trusted_self_hosted" ? issuer : null }); setNotice({ message: t("authorPortal.requestSaved"), tone: "success" }); } catch (error) { setNotice({ message: readErrorMessage(error), tone: "danger" }); } };
  return <div className="space-y-5"><PageHeader eyebrow={t("authorPortal.eyebrow")} title={t("authorPortal.become")} description={t("authorPortal.becomeDescription")} />{notice && <ToastNotice message={notice.message} tone={notice.tone} onDismiss={() => setNotice(null)} />}<Card className="space-y-4"><SectionHeader className="-mx-4 -mt-4" title={t("authorPortal.become")} /><Field label={t("authorPortal.mode")}><Select value={mode} onChange={(event) => setMode(event.target.value as AuthorMode)}><option value="talpaversum_hosted">{t("authorPortal.mode.talpaversum_hosted")}</option><option value="trusted_self_hosted">{t("authorPortal.mode.trusted_self_hosted")}</option></Select></Field><div className="grid gap-3 md:grid-cols-2"><Field label={t("authorPortal.displayName")}><Input value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label={t("authorPortal.contactEmail")}><Input type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></Field></div><Field label={t("authorPortal.descriptionLabel")}><textarea className="min-h-24 w-full rounded-hc-md border border-hc-outline bg-hc-bg p-3" value={description} onChange={(event) => setDescription(event.target.value)} /></Field>{mode === "trusted_self_hosted" && <div className="grid gap-3 md:grid-cols-2"><Field label={t("authorPortal.publicJwks")}><textarea className="min-h-28 w-full rounded-hc-md border border-hc-outline bg-hc-bg p-3 font-mono text-xs" value={jwks} onChange={(event) => setJwks(event.target.value)} /></Field><Field label={t("authorPortal.externalIssuer")}><Input value={issuer} onChange={(event) => setIssuer(event.target.value)} /></Field></div>}<label className="flex gap-2"><input type="checkbox" checked={terms} onChange={(event) => setTerms(event.target.checked)} />{t("authorPortal.acceptTerms")}</label><Button onClick={() => void save()}>{t("authorPortal.saveDraft")}</Button></Card><Card className="p-0"><SectionHeader title={t("authorPortal.myRequests")} />{overview.data?.requests.length ? <Table className="rounded-none border-x-0"><tbody>{overview.data.requests.map((item) => <tr key={item.request_id}><td>{item.requested_display_name}</td><td><StatusBadge>{t(`authorPortal.status.${item.status}`)}</StatusBadge></td><td>{["draft", "needs_changes"].includes(item.status) && <Button size="sm" onClick={() => void submit.mutateAsync(item.request_id)}>{t("authorPortal.submit")}</Button>}</td></tr>)}</tbody></Table> : <EmptyState>{t("authorPortal.noRequests")}</EmptyState>}</Card></div>;
}
