import { useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";

import { readErrorMessage } from "../../../data/api/read-error-message";
import { useLocalization } from "../../../localization/LocalizationProvider";
import { Button } from "../../../ui-kit/components/Button";
import { Card } from "../../../ui-kit/components/Card";
import { Input } from "../../../ui-kit/components/Input";
import { EmptyState, Field, MetricStrip, PageHeader, SectionHeader, StatusBadge } from "../../../ui-kit/components/Page";
import { Select } from "../../../ui-kit/components/Select";
import { Table } from "../../../ui-kit/components/Table";
import { ToastNotice } from "../../../ui-kit/components/ToastNotice";
import { authorPortalRequests, useAuthorActivity, useAuthorApps, useAuthorMembers, useAuthorOverview, useAuthorPortalMutation, useCatalogSubmissions, useGitConnections, useGitRepositories, type AuthorApp, type AuthorProfile } from "./api";

const tone = (status: string): "neutral" | "success" | "warning" | "danger" | "info" => ["approved", "active", "ready_for_review", "running", "published"].includes(status) ? "success" : ["rejected", "revoked", "manifest_invalid", "disabled"].includes(status) ? "danger" : ["submitted", "pending_review", "needs_changes", "runtime_pending", "suspended"].includes(status) ? "warning" : "neutral";

export function AuthorWorkspacePage() {
  const { t } = useLocalization(); const { authorId = "" } = useParams(); const navigate = useNavigate(); const section = useLocation().pathname.split("/")[4] ?? "overview";
  const overview = useAuthorOverview(); const profiles = overview.data?.profiles ?? []; const profile = profiles.find((item) => item.author_id === authorId);
  const [notice, setNotice] = useState<{ message: string; tone: "success" | "danger" } | null>(null);
  const notify = async (action: () => Promise<unknown>, success: string) => { try { await action(); setNotice({ message: success, tone: "success" }); } catch (error) { setNotice({ message: readErrorMessage(error), tone: "danger" }); } };
  if (overview.isLoading) return <Card><EmptyState>{t("common.loading")}</EmptyState></Card>;
  if (!profile) return <Card><EmptyState>{t("authorPortal.noProfiles")}</EmptyState></Card>;
  const switchAuthor = (next: string) => { localStorage.setItem("hc.activeAuthorId", next); navigate(`/core/author/${encodeURIComponent(next)}/${section}`); };
  const body = section === "team" ? <Team authorId={authorId} notify={notify} /> : section === "git" ? <Git authorId={authorId} notify={notify} /> : section === "applications" ? <Applications authorId={authorId} notify={notify} /> : section === "licensing" ? <Licensing profile={profile} /> : section === "catalog" ? <Catalog authorId={authorId} notify={notify} /> : section === "activity" ? <Activity authorId={authorId} /> : <Overview authorId={authorId} />;
  return <div className="space-y-5"><PageHeader eyebrow={t("authorPortal.eyebrow")} title={profile.display_name} description={t("authorPortal.description")} /><Card><Field label={t("authorPortal.activeAuthor")} hint={authorId}><Select value={authorId} onChange={(event) => switchAuthor(event.target.value)}>{profiles.map((item) => <option key={item.author_id} value={item.author_id}>{item.display_name}</option>)}</Select></Field></Card>{notice && <ToastNotice message={notice.message} tone={notice.tone} onDismiss={() => setNotice(null)} />}{body}</div>;
}

function Overview({ authorId }: { authorId: string }) { const { t } = useLocalization(); const apps = useAuthorApps("workspace", authorId); const catalog = useCatalogSubmissions("workspace", authorId); const activity = useAuthorActivity(authorId); return <><MetricStrip items={[{ label: t("authorPortal.applications"), value: apps.data?.items.length ?? 0 }, { label: t("authorPortal.catalogSubmissions"), value: catalog.data?.items.length ?? 0 }, { label: t("authorPortal.activity"), value: activity.data?.items.length ?? 0 }]} /><div className="flex gap-3"><Link className="text-hc-primary" to={`/core/author/${authorId}/applications`}>{t("authorPortal.applications")}</Link><Link className="text-hc-primary" to={`/core/author/${authorId}/git`}>{t("authorPortal.gitConnections")}</Link></div></>; }

function Team({ authorId, notify }: { authorId: string; notify: Notify }) { const { t } = useLocalization(); const members = useAuthorMembers(authorId); const save = useAuthorPortalMutation(authorPortalRequests.saveMember); const [userId, setUserId] = useState(""); const [role, setRole] = useState("developer"); return <Card className="p-0"><SectionHeader title={t("authorPortal.members")} description={t("authorPortal.membersDescription")} />{members.data?.items.length ? <Table className="rounded-none border-x-0"><tbody>{members.data.items.map((item) => <tr key={item.user_id}><td>{item.email}</td><td>{t(`authorPortal.role.${item.role}`)}</td><td>{t(`authorPortal.status.${item.status}`)}</td></tr>)}</tbody></Table> : <EmptyState>{t("authorPortal.noMembers")}</EmptyState>}<div className="grid gap-3 border-t border-hc-outline p-4 md:grid-cols-[1fr_12rem_auto]"><Input value={userId} onChange={(event) => setUserId(event.target.value)} placeholder={t("authorPortal.userId")} /><Select value={role} onChange={(event) => setRole(event.target.value)}>{["owner", "manager", "developer", "licensing", "viewer"].map((item) => <option key={item}>{item}</option>)}</Select><Button onClick={() => void notify(() => save.mutateAsync({ authorId, user_id: userId, role }), t("authorPortal.memberSaved"))}>{t("authorPortal.addMember")}</Button></div></Card>; }

function Git({ authorId, notify }: { authorId: string; notify: Notify }) { const { t } = useLocalization(); const connections = useGitConnections(authorId); const [token, setToken] = useState(""); const [connectionId, setConnectionId] = useState(""); const [repository, setRepository] = useState(""); const repos = useGitRepositories(connectionId); const connect = useAuthorPortalMutation(authorPortalRequests.connectGitHub); return <div className="space-y-4"><Card className="space-y-3"><SectionHeader className="-mx-4 -mt-4" title={t("authorPortal.connectGitHub")} description={t("authorPortal.gitSecurityHelp")} /><Input type="password" value={token} onChange={(event) => setToken(event.target.value)} placeholder={t("authorPortal.githubToken")} /><Button onClick={() => void notify(() => connect.mutateAsync({ author_id: authorId, token }), t("authorPortal.gitConnected"))}>{t("authorPortal.connect")}</Button></Card><Card className="p-0"><SectionHeader title={t("authorPortal.gitConnections")} />{connections.data?.items.map((item) => <button className="block w-full border-t border-hc-outline p-3 text-left" key={item.connection_id} onClick={() => setConnectionId(item.connection_id)}>{item.provider}: {item.account_login}</button>)}</Card>{connectionId && <Card><Field label={t("authorPortal.repository")}><Select value={repository} onChange={(event) => setRepository(event.target.value)}><option value="">{t("authorPortal.selectRepository")}</option>{repos.data?.items.map((item) => <option key={item.id} value={item.full_name}>{item.full_name}</option>)}</Select></Field></Card>}</div>; }

function Applications({ authorId, notify }: { authorId: string; notify: Notify }) { const { t } = useLocalization(); const apps = useAuthorApps("workspace", authorId); const action = useAuthorPortalMutation(authorPortalRequests.appAction); const submit = useAuthorPortalMutation(authorPortalRequests.submitCatalog); const buttons = (app: AuthorApp) => <div className="flex flex-wrap gap-2">{app.status === "ready_for_review" && <Button size="sm" onClick={() => void notify(() => action.mutateAsync({ appId: app.author_app_id, action: "submit" }), t("authorPortal.appSubmitted"))}>{t("authorPortal.submit")}</Button>}{app.status === "approved" && app.runtime_management === "talpaversum_managed" && <Button size="sm" onClick={() => void notify(() => action.mutateAsync({ appId: app.author_app_id, action: "request_runtime" }), t("authorPortal.runtimeRequested"))}>{t("authorPortal.requestRuntime")}</Button>}{["approved", "running", "runtime_approved"].includes(app.status) && <Button size="sm" variant="outlined" onClick={() => void notify(() => submit.mutateAsync(app.author_app_id), t("authorPortal.catalogSubmitted"))}>{t("authorPortal.submitCatalog")}</Button>}</div>; return <Card className="p-0"><SectionHeader title={t("authorPortal.applications")} />{apps.data?.items.length ? <Table className="rounded-none border-x-0"><tbody>{apps.data.items.map((app) => <tr key={app.author_app_id}><td>{app.display_name}<div className="text-xs text-hc-muted">{app.app_id}</div></td><td><StatusBadge tone={tone(app.status)}>{t(`authorPortal.status.${app.status}`)}</StatusBadge></td><td>{buttons(app)}</td></tr>)}</tbody></Table> : <EmptyState>{t("authorPortal.noApplications")}</EmptyState>}</Card>; }

function Licensing({ profile }: { profile: AuthorProfile }) { const { t } = useLocalization(); return <Card className="space-y-3"><StatusBadge>{t(`authorPortal.mode.${profile.operating_mode}`)}</StatusBadge><p>{t(`authorPortal.licensing.${profile.operating_mode}`)}</p>{profile.operating_mode === "talpaversum_hosted" ? <Link className="text-hc-primary" to="/core/licensing">{t("authorPortal.openLicensing")}</Link> : <div>{profile.external_issuer_url ?? t("authorPortal.issuerNotConfigured")}</div>}</Card>; }
function Catalog({ authorId }: { authorId: string; notify: Notify }) { const { t } = useLocalization(); const query = useCatalogSubmissions("workspace", authorId); return <Card className="p-0"><SectionHeader title={t("authorPortal.catalogSubmissions")} />{query.data?.items.length ? <Table className="rounded-none border-x-0"><tbody>{query.data.items.map((item) => <tr key={item.submission_id}><td>{item.display_name ?? item.app_id}</td><td><StatusBadge tone={tone(item.status)}>{t(`authorPortal.status.${item.status}`)}</StatusBadge></td></tr>)}</tbody></Table> : <EmptyState>{t("authorPortal.noCatalogSubmissions")}</EmptyState>}</Card>; }
function Activity({ authorId }: { authorId: string }) { const { t } = useLocalization(); const query = useAuthorActivity(authorId); return <Card className="p-0"><SectionHeader title={t("authorPortal.activity")} />{query.data?.items.length ? <Table className="rounded-none border-x-0"><tbody>{query.data.items.map((item) => <tr key={item.event_id}><td>{t(`authorPortal.event.${item.action}`)}</td><td>{new Date(item.created_at).toLocaleString()}</td></tr>)}</tbody></Table> : <EmptyState>{t("authorPortal.noActivity")}</EmptyState>}</Card>; }
type Notify = (action: () => Promise<unknown>, success: string) => Promise<void>;
