const en = {
  "apps.title": "Applications", "apps.admin": "Admin", "apps.description": "Catalog discovery, instance installation, and tenant license activation.",
  "apps.permissionDenied": "You do not have permission to manage applications.", "apps.installable": "Installable", "apps.published": "Published", "apps.installed": "Installed",
  "apps.updateAttention": "Application update attention", "apps.appSignals": "{{count}} app signals reported", "apps.catalogUpdates": "{{count}} catalog updates available",
  "apps.staleSnapshots": "{{count}} catalog snapshots stale", "apps.updateAttentionDescription": "Installed apps can report update signals, and Core compares them with matching catalog entries. Review signals before refreshing artifacts; clear signals that are informational or already handled.",
  "apps.reviewInstalled": "Review installed apps", "apps.notFound": "Application not found.", "apps.installedNotFound": "Installed application not found.",
  "apps.addApplication": "Add application", "apps.addApplicationDescription": "Fetch an application manifest directly into the local catalog.", "apps.manifestBaseUrl": "Manifest base URL",
  "apps.summary": "Summary", "apps.summaryPlaceholder": "Short operator-facing note", "apps.trust": "Trust", "apps.fetching": "Fetching...", "apps.addToCatalog": "Add to catalog",
  "apps.availableApplications": "Available applications", "apps.requireLicenseCount": "{{count}} require a tenant license.", "apps.entriesCount": "{{count}} entries", "apps.searchCatalog": "Search catalog",
  "apps.installedApplications": "Installed applications", "apps.installedDescription": "Runtime state for this Core instance.", "apps.installedCount": "{{count}} installed", "apps.searchInstalled": "Search installed applications",
  "apps.tenantLicenseSelection": "Tenant license selection", "apps.selectApp": "Select app", "apps.storedLicense": "Stored license", "apps.fallbackSelection": "Fallback selection",
  "apps.licenseBinding": "License binding", "apps.licenseBindingDescription": "Select the entitlement used by an installed application. Activation and import remain in the main Licensing area.",
  "apps.openMainLicensing": "Open Licensing", "apps.manageLicense": "Manage license",
  "apps.selectedSuffix": "selected", "apps.setSelection": "Set selection", "apps.clear": "Clear", "apps.offlineImport": "Offline import", "apps.pasteLicense": "Paste license bundle or token",
  "apps.importing": "Importing...", "apps.importLicense": "Import license", "apps.catalogFeeds": "Catalog feeds", "apps.catalogFeedsDescription": "Remote feeds that can populate the local catalog.",
  "apps.sourcesCount": "{{count}} sources", "apps.feedName": "Feed name", "apps.addFeed": "Add feed", "apps.noFeedSources": "No feed sources yet.", "apps.lastSync": "Last sync: {{date}}",
  "apps.autoRefresh": "Auto refresh", "apps.sync": "Sync", "apps.backToCatalog": "Back to catalog", "apps.licenseRequired": "license required", "apps.free": "free",
  "apps.publishedToFeed": "published to feed", "apps.source": "Source", "apps.runtime": "Runtime", "apps.noNamespace": "no namespace", "apps.noSummary": "No summary",
  "apps.licenseIssuer": "License issuer", "apps.installApplication": "Install application", "apps.activateLicense": "Activate license", "apps.openLicensing": "Open licensing",
  "apps.unpublish": "Unpublish", "apps.publish": "Publish", "apps.removeFromCatalog": "Remove from catalog", "apps.loadingCatalog": "Loading catalog...", "apps.noCatalogEntries": "No catalog entries yet.",
  "apps.license": "License", "apps.required": "required", "apps.feed": "feed", "apps.install": "Install", "apps.backToInstalled": "Back to installed apps",
  "apps.updateSignal": "update signal", "apps.catalogUpdateAvailable": "catalog update available", "apps.managedRuntime": "Core-managed runtime", "apps.runtimeOwner": "Runtime owner",
  "apps.external": "External", "apps.entitlement": "Entitlement", "apps.validTo": "{{tier}}, valid to {{date}}", "apps.noActiveEntitlement": "No active entitlement", "apps.languages": "Languages",
  "apps.catalogState": "Catalog state", "apps.notChecked": "Not checked", "apps.updateReportedBy": "Update reported by {{source}}", "apps.noNote": "No note", "apps.checkUpdate": "Check update",
  "apps.clearSignal": "Clear signal", "apps.issueToken": "Issue token", "apps.rotateRuntimeToken": "Rotate runtime token", "apps.updateRuntime": "Update runtime", "apps.stopRuntime": "Stop runtime",
  "apps.refreshCatalog": "Refresh catalog", "apps.refreshArtifact": "Refresh artifact", "apps.uninstall": "Uninstall", "apps.loadingInstalled": "Loading installed apps...", "apps.noInstalled": "No installed apps.",
  "apps.installationStatus": "Installation", "apps.licenseStatus": "License", "apps.uiIntegration": "UI integration", "apps.lastHealthCheck": "Last health check", "apps.availabilityReason": "Availability reason",
  "apps.installation.installed": "Installed", "apps.installation.disabled": "Disabled", "apps.installation.installing": "Installing", "apps.installation.updating": "Updating", "apps.installation.failed": "Failed",
  "apps.licenseStatus.not_required": "Not required", "apps.licenseStatus.active": "Active", "apps.licenseStatus.missing": "Missing", "apps.licenseStatus.expired": "Expired", "apps.licenseStatus.revoked": "Revoked", "apps.licenseStatus.invalid": "Invalid",
  "apps.uiStatus.ready": "Ready", "apps.uiStatus.missing": "Missing", "apps.uiStatus.invalid": "Invalid", "apps.uiStatus.unreachable": "Unreachable",
  "apps.availability.available": "Available", "apps.availability.degraded": "Degraded", "apps.availability.blocked": "Blocked", "apps.availability.unavailable": "Unavailable", "apps.availability.disabled": "Disabled",
  "apps.reason.none": "No blocking condition", "apps.reason.runtime_unreachable": "The application container may be running, but Core cannot reach its health endpoint.", "apps.reason.runtime_degraded": "Runtime degraded: the application reported a dependency or database health failure.", "apps.reason.runtime_stopped": "The managed application runtime is stopped.", "apps.reason.license_missing": "The application runtime is healthy, but the required license is missing.", "apps.reason.license_expired": "The required license has expired.", "apps.reason.license_revoked": "The required license has been revoked.", "apps.reason.ui_missing": "The application runtime is healthy, but its UI integration is missing.", "apps.reason.ui_unreachable": "Core cannot reach the application UI artifact.", "apps.reason.application_disabled": "The application was disabled by an administrator.", "apps.reason.installation_failed": "The application installation failed.",
  "apps.runDiagnostics": "Run diagnostics", "apps.runningDiagnostics": "Running diagnostics...", "apps.diagnostics": "Diagnostics", "apps.diagnosticStatus.passed": "Passed", "apps.diagnosticStatus.failed": "Failed", "apps.diagnosticStatus.warning": "Warning",
  "apps.diagnostic.dns": "Core DNS resolution", "apps.diagnostic.http": "HTTP connection", "apps.diagnostic.health": "Health endpoint", "apps.diagnostic.manifest": "Manifest endpoint", "apps.diagnostic.ui_artifact": "UI artifact", "apps.diagnostic.license": "License", "apps.diagnostic.trusted_origin": "Trusted origin",
  "apps.updates": "Updates", "apps.noneSelected": "none selected", "apps.signal": "signal", "apps.available": "available", "apps.current": "current", "apps.tokenTitle": "App token",
  "apps.tokenDescription": "Short-lived app token for Core app-auth endpoints. Expires {{date}}.", "apps.copyToken": "Copy token", "apps.installApp": "Install app", "apps.update": "Update",
  "apps.externalService": "External service", "apps.externalServiceDescription": "Install the app registry record and use its existing base URL.", "apps.stageOnly": "Stage only",
  "apps.stageOnlyDescription": "Save the selected plan without installing the runtime registry entry.", "apps.managedCompose": "Core-managed compose",
  "apps.managedComposeDescription": "Let Core approve and run the app compose bundle when runtime support exists.", "apps.deploymentPlan": "Deployment plan", "apps.mode": "Mode", "apps.service": "Service",
  "apps.internalUrl": "Internal URL", "apps.composeProject": "Compose project", "apps.composeFile": "Compose file", "apps.notDeclared": "not declared", "apps.hostAccess": "Host access",
  "apps.allowed": "allowed", "apps.blocked": "blocked", "apps.approveManagedRuntime": "Approve Core-managed runtime {{operation}}",
  "apps.approveManagedRuntimeDescription": "I reviewed the manifest and package hashes and authorize Core to build and {{operation}} this Compose service.",
  "apps.approvalRequirements": "The catalog entry must declare package URL, package SHA-256, and Compose file before this runtime can be approved.",
  "apps.runtimeUpdateRunning": "Runtime update is running...", "apps.installationRunning": "Installation is running...", "apps.running": "Running...", "apps.approve": "Approve",
  "apps.start": "start", "apps.replace": "replace", "apps.uninstallTitle": "Uninstall app", "apps.confirmUninstall": "Confirm uninstall",
  "apps.uninstallDescription": "Remove this app from Core. Core-managed containers will also be removed; external runtimes are not affected.", "apps.uninstallRunning": "Uninstall is running...",
  "apps.uninstallCompleted": "Uninstall completed", "apps.uninstallFailed": "Uninstall failed", "apps.retry": "Retry",
  "apps.status.broken": "Broken", "apps.status.missingArtifact": "UI artifact is missing.", "apps.status.licenseInactive": "License inactive", "apps.status.licenseMissing": "License missing",
  "apps.status.tenantLicenseInactive": "The selected tenant license is inactive.", "apps.status.runtimeBlocked": "Runtime is blocked until a license is available.",
  "apps.status.hidden": "Hidden", "apps.status.hiddenDescription": "The application is not present in runtime navigation.", "apps.status.ready": "Ready", "apps.status.available": "Available",
  "apps.status.disabled": "Disabled", "apps.status.disabledDescription": "The installed application is disabled.", "apps.status.catalogLicenseInactive": "The selected catalog license is inactive.",
  "apps.status.catalogRuntimeBlocked": "Installation requires an active license.", "apps.error.httpOrigin": "This HTTP origin is not trusted. Add it under Platform settings / Trusted origins and try again.",
  "apps.message.catalogRefreshed": "Catalog entry {{id}} was refreshed.", "apps.message.feedSaved": "Catalog feed {{name}} was saved.",
  "apps.message.feedSynced": "Catalog feed {{name}} synced: {{imported}}/{{total}} imported{{suffix}}.", "apps.message.failedSuffix": ", {{count}} failed",
  "apps.message.sourceState": "{{name}} was {{state}}.", "apps.message.autoRefreshState": "{{name}} automatic refresh was {{state}}.",
  "apps.message.runtimeCatalogRequired": "A matching catalog entry is required before a managed runtime can be updated.", "apps.message.runtimeUpdated": "{{name}} runtime was updated.",
  "apps.message.staged": "{{name}} was staged for installation.", "apps.message.installed": "{{name}} was installed.", "apps.message.removedCatalog": "{{name}} was removed from catalog.",
  "apps.message.publication": "{{name}} was {{state}} this instance feed.", "apps.message.publishedTo": "published to", "apps.message.removedFrom": "removed from",
  "apps.message.uninstalled": "{{name}} was uninstalled.", "apps.message.artifactRefreshed": "{{name}} artifact was refreshed.",
  "apps.message.updateAvailable": "{{name}} has an update available ({{from}} -> {{to}}).", "apps.message.upToDate": "{{name}} is up to date ({{version}}).",
  "apps.message.updateUnknown": "{{name}} update state is unknown. Refresh artifact once to store a baseline manifest hash.",
  "apps.message.catalogFromInstalled": "{{name}} catalog entry was refreshed from installed app.", "apps.message.signalCleared": "{{name}} update signal was cleared.",
  "apps.message.tokenIssued": "{{name}} app token was issued.", "apps.message.runtimeStopped": "{{name}} runtime was stopped.",
  "apps.message.tokenRotated": "{{name}} runtime token was rotated; valid until {{date}}.", "apps.message.selectionUpdated": "License selection was updated.",
  "apps.message.selectionCleared": "License selection was cleared.", "apps.message.offlineImported": "Offline token ingest OK ({{result}}).",
  "apps.value.manual": "Manual", "apps.value.dev": "Development", "apps.value.unverified": "Unverified", "apps.value.verified": "Verified",
  "apps.value.official": "Official", "apps.value.draft": "Draft", "apps.value.published": "Published", "apps.value.external": "External",
  "apps.value.stage_only": "Stage only", "apps.value.compose": "Compose", "apps.value.feed": "Feed", "apps.value.same": "Current", "apps.value.stale": "Stale",
} as const;

const cs: Record<keyof typeof en, string> = {
  ...en,
  "apps.title": "Aplikace", "apps.admin": "Administrace", "apps.description": "Vyhledávání v katalogu, instalace do instance a aktivace licencí tenantů.",
  "apps.permissionDenied": "Nemáte oprávnění spravovat aplikace.", "apps.installable": "K instalaci", "apps.published": "Publikované", "apps.installed": "Nainstalované",
  "apps.updateAttention": "Aplikace vyžadují pozornost", "apps.appSignals": "Nahlášené signály aplikací: {{count}}", "apps.catalogUpdates": "Dostupné aktualizace katalogu: {{count}}",
  "apps.staleSnapshots": "Zastaralé snímky katalogu: {{count}}", "apps.updateAttentionDescription": "Nainstalované aplikace mohou hlásit dostupné aktualizace a Core je porovnává s odpovídajícími záznamy katalogu. Před obnovením artefaktů signály zkontrolujte a vyřešené signály smažte.",
  "apps.reviewInstalled": "Zkontrolovat nainstalované aplikace", "apps.notFound": "Aplikace nebyla nalezena.", "apps.installedNotFound": "Nainstalovaná aplikace nebyla nalezena.",
  "apps.addApplication": "Přidat aplikaci", "apps.addApplicationDescription": "Načte manifest aplikace přímo do místního katalogu.", "apps.manifestBaseUrl": "Základní URL manifestu",
  "apps.summary": "Shrnutí", "apps.summaryPlaceholder": "Krátká poznámka pro správce", "apps.trust": "Důvěryhodnost", "apps.fetching": "Načítání...", "apps.addToCatalog": "Přidat do katalogu",
  "apps.availableApplications": "Dostupné aplikace", "apps.requireLicenseCount": "Licenci tenantu vyžaduje: {{count}}.", "apps.entriesCount": "Záznamy: {{count}}", "apps.searchCatalog": "Prohledat katalog",
  "apps.installedApplications": "Nainstalované aplikace", "apps.installedDescription": "Stav běhu aplikací v této instanci Core.", "apps.installedCount": "Nainstalováno: {{count}}", "apps.searchInstalled": "Prohledat nainstalované aplikace",
  "apps.tenantLicenseSelection": "Výběr licence tenantu", "apps.selectApp": "Vyberte aplikaci", "apps.storedLicense": "Uložená licence", "apps.fallbackSelection": "Výchozí výběr",
  "apps.licenseBinding": "Vazba licence", "apps.licenseBindingDescription": "Vyberte entitlement používaný nainstalovanou aplikací. Aktivace a import zůstávají v hlavní sekci Licencování.",
  "apps.openMainLicensing": "Otevřít Licencování", "apps.manageLicense": "Spravovat licenci",
  "apps.selectedSuffix": "vybráno", "apps.setSelection": "Nastavit výběr", "apps.clear": "Vymazat", "apps.pasteLicense": "Vložte licenční balíček nebo token", "apps.importing": "Importování...",
  "apps.importLicense": "Importovat licenci", "apps.catalogFeeds": "Katalogové feedy", "apps.catalogFeedsDescription": "Vzdálené feedy, které mohou naplnit místní katalog.",
  "apps.sourcesCount": "Zdroje: {{count}}", "apps.feedName": "Název feedu", "apps.addFeed": "Přidat feed", "apps.noFeedSources": "Zatím nejsou žádné zdroje feedů.",
  "apps.lastSync": "Poslední synchronizace: {{date}}", "apps.autoRefresh": "Automatické obnovení", "apps.sync": "Synchronizovat", "apps.backToCatalog": "Zpět do katalogu",
  "apps.licenseRequired": "vyžaduje licenci", "apps.free": "zdarma", "apps.publishedToFeed": "publikováno do feedu", "apps.source": "Zdroj", "apps.runtime": "Běhové prostředí",
  "apps.noNamespace": "bez namespace", "apps.noSummary": "Bez shrnutí", "apps.licenseIssuer": "Vydavatel licence", "apps.installApplication": "Nainstalovat aplikaci",
  "apps.activateLicense": "Aktivovat licenci", "apps.openLicensing": "Otevřít licence", "apps.unpublish": "Zrušit publikování", "apps.publish": "Publikovat",
  "apps.removeFromCatalog": "Odebrat z katalogu", "apps.loadingCatalog": "Načítání katalogu...", "apps.noCatalogEntries": "Katalog zatím neobsahuje žádné záznamy.",
  "apps.license": "Licence", "apps.required": "povinná", "apps.install": "Nainstalovat", "apps.backToInstalled": "Zpět na nainstalované aplikace", "apps.updateSignal": "signál aktualizace",
  "apps.catalogUpdateAvailable": "dostupná aktualizace katalogu", "apps.managedRuntime": "Běh spravovaný Core", "apps.runtimeOwner": "Správce běhu", "apps.external": "Externí",
  "apps.entitlement": "Oprávnění", "apps.validTo": "{{tier}}, platné do {{date}}", "apps.noActiveEntitlement": "Žádné aktivní oprávnění", "apps.languages": "Jazyky",
  "apps.catalogState": "Stav katalogu", "apps.notChecked": "Nezkontrolováno", "apps.updateReportedBy": "Aktualizaci nahlásil {{source}}", "apps.noNote": "Bez poznámky",
  "apps.checkUpdate": "Zkontrolovat aktualizaci", "apps.clearSignal": "Vymazat signál", "apps.issueToken": "Vydat token", "apps.rotateRuntimeToken": "Obnovit token běhu",
  "apps.updateRuntime": "Aktualizovat běh", "apps.stopRuntime": "Zastavit běh", "apps.refreshCatalog": "Obnovit katalog", "apps.refreshArtifact": "Obnovit artefakt",
  "apps.uninstall": "Odinstalovat", "apps.loadingInstalled": "Načítání nainstalovaných aplikací...", "apps.noInstalled": "Žádné nainstalované aplikace.", "apps.updates": "Aktualizace",
  "apps.installationStatus": "Instalace", "apps.licenseStatus": "Licence", "apps.uiIntegration": "Integrace UI", "apps.lastHealthCheck": "Poslední kontrola zdraví", "apps.availabilityReason": "Důvod dostupnosti",
  "apps.installation.installed": "Nainstalováno", "apps.installation.disabled": "Zakázáno", "apps.installation.installing": "Instaluje se", "apps.installation.updating": "Aktualizuje se", "apps.installation.failed": "Selhalo",
  "apps.licenseStatus.not_required": "Není vyžadována", "apps.licenseStatus.active": "Aktivní", "apps.licenseStatus.missing": "Chybí", "apps.licenseStatus.expired": "Vypršela", "apps.licenseStatus.revoked": "Odvolaná", "apps.licenseStatus.invalid": "Neplatná",
  "apps.uiStatus.ready": "Připravená", "apps.uiStatus.missing": "Chybí", "apps.uiStatus.invalid": "Neplatná", "apps.uiStatus.unreachable": "Nedostupná",
  "apps.availability.available": "Dostupná", "apps.availability.degraded": "Omezená", "apps.availability.blocked": "Blokovaná", "apps.availability.unavailable": "Nedostupná", "apps.availability.disabled": "Zakázaná",
  "apps.reason.none": "Bez blokujícího problému", "apps.reason.runtime_unreachable": "Kontejner aplikace může běžet, ale Core nedosáhne na jeho health endpoint.", "apps.reason.runtime_degraded": "Omezený běh: aplikace nahlásila chybu databáze nebo jiné závislosti.", "apps.reason.runtime_stopped": "Spravovaný běh aplikace je zastavený.", "apps.reason.license_missing": "Běh aplikace je zdravý, ale chybí vyžadovaná licence.", "apps.reason.license_expired": "Vyžadovaná licence vypršela.", "apps.reason.license_revoked": "Vyžadovaná licence byla odvolána.", "apps.reason.ui_missing": "Běh aplikace je zdravý, ale chybí integrace UI.", "apps.reason.ui_unreachable": "Core nedosáhne na UI artefakt aplikace.", "apps.reason.application_disabled": "Aplikaci zakázal administrátor.", "apps.reason.installation_failed": "Instalace aplikace selhala.",
  "apps.runDiagnostics": "Spustit diagnostiku", "apps.runningDiagnostics": "Probíhá diagnostika...", "apps.diagnostics": "Diagnostika", "apps.diagnosticStatus.passed": "V pořádku", "apps.diagnosticStatus.failed": "Selhalo", "apps.diagnosticStatus.warning": "Varování",
  "apps.diagnostic.dns": "DNS překlad z Core", "apps.diagnostic.http": "HTTP spojení", "apps.diagnostic.health": "Health endpoint", "apps.diagnostic.manifest": "Endpoint manifestu", "apps.diagnostic.ui_artifact": "UI artefakt", "apps.diagnostic.license": "Licence", "apps.diagnostic.trusted_origin": "Důvěryhodný origin",
  "apps.noneSelected": "nic nevybráno", "apps.signal": "signál", "apps.available": "dostupná", "apps.current": "aktuální", "apps.tokenTitle": "Token aplikace",
  "apps.tokenDescription": "Krátkodobý token aplikace pro autentizační endpointy Core. Vyprší {{date}}.", "apps.copyToken": "Kopírovat token", "apps.installApp": "Nainstalovat aplikaci",
  "apps.update": "Aktualizovat", "apps.externalService": "Externí služba", "apps.externalServiceDescription": "Nainstaluje záznam aplikace a použije její existující základní URL.",
  "apps.stageOnly": "Pouze připravit", "apps.stageOnlyDescription": "Uloží vybraný plán bez instalace záznamu běhového prostředí.", "apps.managedCompose": "Compose spravovaný Core",
  "apps.managedComposeDescription": "Core schválí a spustí Compose balíček aplikace, pokud je tato podpora dostupná.", "apps.deploymentPlan": "Plán nasazení",
  "apps.mode": "Režim", "apps.service": "Služba", "apps.internalUrl": "Interní URL", "apps.composeProject": "Compose projekt", "apps.composeFile": "Compose soubor",
  "apps.notDeclared": "neuvedeno", "apps.hostAccess": "Přístup k hostiteli", "apps.allowed": "povolen", "apps.blocked": "blokován",
  "apps.approveManagedRuntime": "Schválit {{operation}} běhu spravovaného Core", "apps.approveManagedRuntimeDescription": "Zkontroloval jsem hashe manifestu a balíčku a povoluji Core tuto Compose službu {{operation}}.",
  "apps.approvalRequirements": "Před schválením musí záznam katalogu uvádět URL balíčku, SHA-256 balíčku a Compose soubor.",
  "apps.runtimeUpdateRunning": "Probíhá aktualizace běhu...", "apps.installationRunning": "Probíhá instalace...", "apps.running": "Probíhá...", "apps.approve": "Schválit",
  "apps.start": "spustit", "apps.replace": "nahradit", "apps.uninstallTitle": "Odinstalovat aplikaci", "apps.confirmUninstall": "Potvrdit odinstalaci",
  "apps.uninstallDescription": "Odebere aplikaci z Core. Kontejnery spravované Core budou také odebrány; externí běhová prostředí nebudou ovlivněna.",
  "apps.uninstallRunning": "Probíhá odinstalace...", "apps.uninstallCompleted": "Odinstalace dokončena", "apps.uninstallFailed": "Odinstalace selhala", "apps.retry": "Zkusit znovu",
  "apps.status.broken": "Nefunkční", "apps.status.missingArtifact": "Chybí artefakt uživatelského rozhraní.", "apps.status.licenseInactive": "Licence není aktivní",
  "apps.status.licenseMissing": "Chybí licence", "apps.status.tenantLicenseInactive": "Vybraná licence tenantu není aktivní.", "apps.status.runtimeBlocked": "Běh je blokován, dokud nebude dostupná licence.",
  "apps.status.hidden": "Skrytá", "apps.status.hiddenDescription": "Aplikace není zobrazena v navigaci.", "apps.status.ready": "Připravená", "apps.status.available": "Dostupná",
  "apps.status.disabled": "Zakázaná", "apps.status.disabledDescription": "Nainstalovaná aplikace je zakázaná.", "apps.status.catalogLicenseInactive": "Vybraná licence katalogu není aktivní.",
  "apps.status.catalogRuntimeBlocked": "Instalace vyžaduje aktivní licenci.", "apps.error.httpOrigin": "Tento HTTP zdroj není důvěryhodný. Přidejte jej v Nastavení platformy / Důvěryhodné zdroje a zkuste to znovu.",
  "apps.message.catalogRefreshed": "Záznam katalogu {{id}} byl obnoven.", "apps.message.feedSaved": "Katalogový feed {{name}} byl uložen.",
  "apps.message.feedSynced": "Katalogový feed {{name}} synchronizován: importováno {{imported}}/{{total}}{{suffix}}.", "apps.message.failedSuffix": ", selhalo {{count}}",
  "apps.message.sourceState": "{{name}}: {{state}}.", "apps.message.autoRefreshState": "Automatické obnovení {{name}}: {{state}}.",
  "apps.message.runtimeCatalogRequired": "Před aktualizací spravovaného běhu je vyžadován odpovídající záznam katalogu.", "apps.message.runtimeUpdated": "Běh {{name}} byl aktualizován.",
  "apps.message.staged": "{{name}} byla připravena k instalaci.", "apps.message.installed": "{{name}} byla nainstalována.", "apps.message.removedCatalog": "{{name}} byla odebrána z katalogu.",
  "apps.message.publication": "{{name}} byla {{state}} feedu této instance.", "apps.message.publishedTo": "publikována do", "apps.message.removedFrom": "odebrána z",
  "apps.message.uninstalled": "{{name}} byla odinstalována.", "apps.message.artifactRefreshed": "Artefakt {{name}} byl obnoven.",
  "apps.message.updateAvailable": "Pro {{name}} je dostupná aktualizace ({{from}} -> {{to}}).", "apps.message.upToDate": "{{name}} je aktuální ({{version}}).",
  "apps.message.updateUnknown": "Stav aktualizace {{name}} není známý. Jednou obnovte artefakt, aby se uložil výchozí hash manifestu.",
  "apps.message.catalogFromInstalled": "Záznam katalogu {{name}} byl obnoven z nainstalované aplikace.", "apps.message.signalCleared": "Signál aktualizace {{name}} byl vymazán.",
  "apps.message.tokenIssued": "Token aplikace {{name}} byl vydán.", "apps.message.runtimeStopped": "Běh {{name}} byl zastaven.",
  "apps.message.tokenRotated": "Token běhu {{name}} byl obnoven; platí do {{date}}.", "apps.message.selectionUpdated": "Výběr licence byl aktualizován.",
  "apps.message.selectionCleared": "Výběr licence byl vymazán.", "apps.message.offlineImported": "Offline token byl importován ({{result}}).",
  "apps.value.manual": "Ruční", "apps.value.dev": "Vývojový", "apps.value.unverified": "Neověřený", "apps.value.verified": "Ověřený",
  "apps.value.official": "Oficiální", "apps.value.draft": "Koncept", "apps.value.published": "Publikováno", "apps.value.external": "Externí",
  "apps.value.stage_only": "Pouze připravit", "apps.value.compose": "Compose", "apps.value.feed": "Feed", "apps.value.same": "Aktuální", "apps.value.stale": "Zastaralý",
};

export const appsResources = { en, cs };
