const en = {
  "nav.auditLog": "Audit log", "audit.title": "Audit log", "audit.eyebrow": "Accounting",
  "audit.description": "Business, security, and administrative events visible in your current access scope.",
  "audit.filters": "Filters", "audit.from": "From", "audit.to": "To", "audit.severity": "Severity",
  "audit.outcome": "Outcome", "audit.eventType": "Event type", "audit.category": "Category",
  "audit.users": "Users", "audit.applications": "Applications", "audit.tenants": "Tenants",
  "audit.platformEvents": "Platform events", "audit.apply": "Apply filters", "audit.clear": "Clear filters",
  "audit.loading": "Loading audit events...", "audit.empty": "No audit events match these filters.",
  "audit.time": "Time", "audit.actor": "Actor", "audit.tenant": "Tenant", "audit.application": "Application",
  "audit.action": "Action", "audit.resource": "Resource", "audit.message": "Message", "audit.detail": "Event detail",
  "audit.id": "ID", "audit.effectiveUser": "Effective user", "audit.sourceService": "Source service",
  "audit.correlationId": "Correlation ID", "audit.requestId": "Request ID", "audit.ipAddress": "IP address",
  "audit.userAgent": "User agent", "audit.metadata": "Sanitized metadata", "audit.loadMore": "Load next page",
  "audit.closeDetail": "Close detail", "audit.forbidden": "You do not have permission to read audit events.",
  "audit.value.success": "Success", "audit.value.failure": "Failure", "audit.value.denied": "Denied",
  "audit.value.unknown": "Unknown", "audit.value.debug": "Debug", "audit.value.info": "Info",
  "audit.value.warning": "Warning", "audit.value.error": "Error", "audit.value.critical": "Critical",
  "audit.value.user": "User", "audit.value.tenant": "Tenant", "audit.value.platform": "Platform",
  "audit.event.auth.login.succeeded": "Login succeeded", "audit.event.auth.login.failed": "Login failed",
  "audit.event.identity.user.created": "User created", "audit.event.identity.user.updated": "User updated",
  "audit.event.app.runtime.installed": "Application runtime installed", "audit.event.app.runtime.started": "Application runtime started",
  "audit.event.app.runtime.stopped": "Application runtime stopped", "audit.event.inventory.item.created": "Inventory item created",
  "audit.event.inventory.item.updated": "Inventory item updated", "audit.event.inventory.item.deleted": "Inventory item deleted",
  "audit.event.inventory.operation.denied": "Inventory operation denied",
  "audit.timeRange": "Time range", "audit.range.15m": "Last 15 min", "audit.range.1h": "Last 1 hour",
  "audit.range.6h": "Last 6 hours", "audit.range.24h": "Last 24 hours", "audit.range.7d": "Last 7 days",
  "audit.range.30d": "Last 30 days", "audit.range.custom": "Custom", "audit.timeInvalid": "Enter a relative expression such as now-1h or an absolute date and time.",
  "audit.timeOrderInvalid": "The start of the range must be before its end.", "audit.addFilter": "Add filter",
  "audit.chooseValues": "Choose values", "audit.searchValues": "Search values", "audit.noValues": "No matching values.",
  "audit.removeFilter": "Remove {{filter}} filter", "audit.allFiltersAdded": "All available filters are active.",
  "audit.clearAll": "Clear all", "audit.clearFilters": "Clear filters", "audit.events": "events",
  "audit.refresh": "Refresh", "audit.refreshing": "Refreshing...", "audit.loadError": "Audit events could not be loaded.",
  "audit.retry": "Retry", "audit.emptySelected": "No audit events match the selected time range and filters.",
  "audit.eventScope": "Event scope", "audit.visibility": "Visibility", "audit.showRaw": "Show raw event",
  "audit.hideRaw": "Hide raw event", "audit.section.summary": "Summary", "audit.section.actor": "Actor",
  "audit.section.target": "Target", "audit.section.request": "Request",
} as const;

const cs: Record<keyof typeof en, string> = {
  ...en,
  "nav.auditLog": "Auditní záznamy", "audit.title": "Auditní záznamy", "audit.eyebrow": "Účtování",
  "audit.description": "Obchodní, bezpečnostní a administrativní události dostupné v aktuálním rozsahu oprávnění.",
  "audit.filters": "Filtry", "audit.from": "Od", "audit.to": "Do", "audit.severity": "Závažnost",
  "audit.outcome": "Výsledek", "audit.eventType": "Typ události", "audit.category": "Kategorie",
  "audit.users": "Uživatelé", "audit.applications": "Aplikace", "audit.tenants": "Tenanty",
  "audit.platformEvents": "Platformní události", "audit.apply": "Použít filtry", "audit.clear": "Vymazat filtry",
  "audit.loading": "Načítání auditních událostí...", "audit.empty": "Filtrům neodpovídají žádné události.",
  "audit.time": "Čas", "audit.actor": "Aktér", "audit.tenant": "Tenant", "audit.application": "Aplikace",
  "audit.action": "Akce", "audit.resource": "Zdroj", "audit.message": "Zpráva", "audit.detail": "Detail události",
  "audit.id": "ID", "audit.effectiveUser": "Efektivní uživatel", "audit.sourceService": "Zdrojová služba",
  "audit.correlationId": "Korelační ID", "audit.requestId": "ID požadavku", "audit.ipAddress": "IP adresa",
  "audit.userAgent": "User agent", "audit.metadata": "Sanitizovaná metadata", "audit.loadMore": "Načíst další stránku",
  "audit.closeDetail": "Zavřít detail", "audit.forbidden": "Nemáte oprávnění číst auditní události.",
  "audit.value.success": "Úspěch", "audit.value.failure": "Selhání", "audit.value.denied": "Zamítnuto",
  "audit.value.unknown": "Neznámý", "audit.value.debug": "Ladění", "audit.value.info": "Informace",
  "audit.value.warning": "Varování", "audit.value.error": "Chyba", "audit.value.critical": "Kritická",
  "audit.value.user": "Uživatel", "audit.value.tenant": "Tenant", "audit.value.platform": "Platforma",
  "audit.event.auth.login.succeeded": "Přihlášení proběhlo úspěšně", "audit.event.auth.login.failed": "Přihlášení selhalo",
  "audit.event.identity.user.created": "Uživatel vytvořen", "audit.event.identity.user.updated": "Uživatel změněn",
  "audit.event.app.runtime.installed": "Běh aplikace nainstalován", "audit.event.app.runtime.started": "Běh aplikace spuštěn",
  "audit.event.app.runtime.stopped": "Běh aplikace zastaven", "audit.event.inventory.item.created": "Položka inventáře vytvořena",
  "audit.event.inventory.item.updated": "Položka inventáře změněna", "audit.event.inventory.item.deleted": "Položka inventáře odstraněna",
  "audit.event.inventory.operation.denied": "Operace inventáře zamítnuta",
  "audit.timeRange": "Časový rozsah", "audit.range.15m": "Posledních 15 min", "audit.range.1h": "Poslední hodina",
  "audit.range.6h": "Posledních 6 hodin", "audit.range.24h": "Posledních 24 hodin", "audit.range.7d": "Posledních 7 dní",
  "audit.range.30d": "Posledních 30 dní", "audit.range.custom": "Vlastní", "audit.timeInvalid": "Zadejte relativní výraz jako now-1h nebo absolutní datum a čas.",
  "audit.timeOrderInvalid": "Začátek rozsahu musí být před jeho koncem.", "audit.addFilter": "Přidat filtr",
  "audit.chooseValues": "Vyberte hodnoty", "audit.searchValues": "Hledat hodnoty", "audit.noValues": "Žádné odpovídající hodnoty.",
  "audit.removeFilter": "Odebrat filtr {{filter}}", "audit.allFiltersAdded": "Všechny dostupné filtry jsou aktivní.",
  "audit.clearAll": "Vymazat vše", "audit.clearFilters": "Vymazat filtry", "audit.events": "událostí",
  "audit.refresh": "Obnovit", "audit.refreshing": "Obnovování...", "audit.loadError": "Auditní události se nepodařilo načíst.",
  "audit.retry": "Zkusit znovu", "audit.emptySelected": "Vybranému času a filtrům neodpovídají žádné auditní události.",
  "audit.eventScope": "Rozsah události", "audit.visibility": "Viditelnost", "audit.showRaw": "Zobrazit nezpracovanou událost",
  "audit.hideRaw": "Skrýt nezpracovanou událost", "audit.section.summary": "Souhrn", "audit.section.actor": "Aktér",
  "audit.section.target": "Cíl", "audit.section.request": "Požadavek",
};

export const auditResources = { en, cs };
