const en = {
  "nav.auditLog": "Audit log", "audit.title": "Audit log", "audit.eyebrow": "Accounting",
  "audit.description": "Business, security, and administrative events visible in your current access scope.",
  "audit.filters": "Filters", "audit.from": "From", "audit.to": "To", "audit.severity": "Severity",
  "audit.outcome": "Outcome", "audit.eventType": "Event type", "audit.category": "Category",
  "audit.users": "Users", "audit.applications": "Applications", "audit.tenants": "Tenants",
  "audit.platformEvents": "Platform events", "audit.apply": "Apply filters", "audit.clear": "Clear filters",
  "audit.loading": "Loading audit events...", "audit.empty": "No audit events match these filters.",
  "audit.time": "Time", "audit.actor": "Actor", "audit.tenant": "Tenant", "audit.application": "Application",
  "audit.action": "Action", "audit.resource": "Resource", "audit.message": "Message", "audit.detail": "Event detail",
  "audit.id": "ID", "audit.effectiveUser": "Effective user", "audit.sourceService": "Source service",
  "audit.correlationId": "Correlation ID", "audit.requestId": "Request ID", "audit.ipAddress": "IP address",
  "audit.userAgent": "User agent", "audit.metadata": "Sanitized metadata", "audit.loadMore": "Load next page",
  "audit.closeDetail": "Close detail", "audit.forbidden": "You do not have permission to read audit events.",
  "audit.value.success": "Success", "audit.value.failure": "Failure", "audit.value.denied": "Denied",
  "audit.value.unknown": "Unknown", "audit.value.debug": "Debug", "audit.value.info": "Info",
  "audit.value.warning": "Warning", "audit.value.error": "Error", "audit.value.critical": "Critical",
  "audit.value.user": "User", "audit.value.tenant": "Tenant", "audit.value.platform": "Platform",
  "audit.event.auth.login.succeeded": "Login succeeded", "audit.event.auth.login.failed": "Login failed",
  "audit.event.identity.user.created": "User created", "audit.event.identity.user.updated": "User updated",
  "audit.event.app.runtime.installed": "Application runtime installed", "audit.event.app.runtime.started": "Application runtime started",
  "audit.event.app.runtime.stopped": "Application runtime stopped", "audit.event.inventory.item.created": "Inventory item created",
  "audit.event.inventory.item.updated": "Inventory item updated", "audit.event.inventory.item.deleted": "Inventory item deleted",
  "audit.event.inventory.operation.denied": "Inventory operation denied",
} as const;

const cs: Record<keyof typeof en, string> = {
  ...en,
  "nav.auditLog": "Auditní záznamy", "audit.title": "Auditní záznamy", "audit.eyebrow": "Účtování",
  "audit.description": "Obchodní, bezpečnostní a administrativní události dostupné v aktuálním rozsahu oprávnění.",
  "audit.filters": "Filtry", "audit.from": "Od", "audit.to": "Do", "audit.severity": "Závažnost",
  "audit.outcome": "Výsledek", "audit.eventType": "Typ události", "audit.category": "Kategorie",
  "audit.users": "Uživatelé", "audit.applications": "Aplikace", "audit.tenants": "Tenanty",
  "audit.platformEvents": "Platformní události", "audit.apply": "Použít filtry", "audit.clear": "Vymazat filtry",
  "audit.loading": "Načítání auditních událostí...", "audit.empty": "Filtrům neodpovídají žádné události.",
  "audit.time": "Čas", "audit.actor": "Aktér", "audit.tenant": "Tenant", "audit.application": "Aplikace",
  "audit.action": "Akce", "audit.resource": "Zdroj", "audit.message": "Zpráva", "audit.detail": "Detail události",
  "audit.id": "ID", "audit.effectiveUser": "Efektivní uživatel", "audit.sourceService": "Zdrojová služba",
  "audit.correlationId": "Korelační ID", "audit.requestId": "ID požadavku", "audit.ipAddress": "IP adresa",
  "audit.userAgent": "User agent", "audit.metadata": "Sanitizovaná metadata", "audit.loadMore": "Načíst další stránku",
  "audit.closeDetail": "Zavřít detail", "audit.forbidden": "Nemáte oprávnění číst auditní události.",
  "audit.value.success": "Úspěch", "audit.value.failure": "Selhání", "audit.value.denied": "Zamítnuto",
  "audit.value.unknown": "Neznámý", "audit.value.debug": "Ladění", "audit.value.info": "Informace",
  "audit.value.warning": "Varování", "audit.value.error": "Chyba", "audit.value.critical": "Kritická",
  "audit.value.user": "Uživatel", "audit.value.tenant": "Tenant", "audit.value.platform": "Platforma",
  "audit.event.auth.login.succeeded": "Přihlášení proběhlo úspěšně", "audit.event.auth.login.failed": "Přihlášení selhalo",
  "audit.event.identity.user.created": "Uživatel vytvořen", "audit.event.identity.user.updated": "Uživatel změněn",
  "audit.event.app.runtime.installed": "Běh aplikace nainstalován", "audit.event.app.runtime.started": "Běh aplikace spuštěn",
  "audit.event.app.runtime.stopped": "Běh aplikace zastaven", "audit.event.inventory.item.created": "Položka inventáře vytvořena",
  "audit.event.inventory.item.updated": "Položka inventáře změněna", "audit.event.inventory.item.deleted": "Položka inventáře odstraněna",
  "audit.event.inventory.operation.denied": "Operace inventáře zamítnuta",
};

export const auditResources = { en, cs };
