const en: Record<string, string> = {
  "nav.authorPortal": "Author Portal",
  "authorPortal.title": "Author Portal",
  "authorPortal.developerTools": "Developer Tools",
  "authorPortal.developerToolsDescription": "Build, install and test private applications without official registry approval.",
  "authorPortal.privateApps": "Private applications",
  "authorPortal.officialServices": "Optional official services",
  "authorPortal.officialServicesDescription": "These links only appear when this instance provides and configures the relevant service.",
  "authorPortal.registryAdministration": "Registry Administration",
  "authorPortal.capabilityUnavailable": "This service is not available or configured on this instance.",
  "authorPortal.available": "Available",
  "authorPortal.unavailable": "Unavailable",
  "authorPortal.openTool": "Open tool",
  "authorPortal.activeAuthor": "Active author",
  "authorPortal.eyebrow": "Application authoring",
  "authorPortal.description": "Manage author identities, source repositories, applications, licensing and catalog submissions.",
  "authorPortal.requests": "Requests",
  "authorPortal.profiles": "Author profiles",
  "authorPortal.applications": "Applications",
  "authorPortal.catalogSubmissions": "Catalog submissions",
  "authorPortal.private": "Private",
  "authorPortal.official": "Official trust",
  "authorPortal.emptyOverview": "Choose an authoring mode to begin. Private development stays local and does not require registry approval.",
  "authorPortal.become": "Become an Author",
  "authorPortal.becomeDescription": "Request an official author identity, or follow the local workflow for private applications.",
  "authorPortal.mode": "Mode",
  "authorPortal.mode.talpaversum_hosted": "Hosted on Talpaversum",
  "authorPortal.mode.talpaversum_hosted.description": "Talpaversum operates the registry identity, runtime, signing keys, licensing and catalog workflow.",
  "authorPortal.mode.talpaversum_hosted.responsibility": "You maintain the source repository and application metadata.",
  "authorPortal.mode.trusted_self_hosted": "Trusted self-hosted",
  "authorPortal.mode.trusted_self_hosted.description": "The official Registry establishes trust, while you operate the runtime, signing key and licensing issuer.",
  "authorPortal.mode.trusted_self_hosted.responsibility": "You are responsible for infrastructure, key custody, updates and issuer availability.",
  "authorPortal.privateGuidance": "Private self-hosted development does not create an official author request. Run the app locally, configure its trusted origin, and install its manifest or private feed.",
  "authorPortal.configureOrigins": "Configure trusted origins",
  "authorPortal.installPrivateApp": "Install a private app",
  "authorPortal.displayName": "Display name",
  "authorPortal.legalName": "Legal or company name",
  "authorPortal.contactEmail": "Contact email",
  "authorPortal.website": "Website",
  "authorPortal.gitProfile": "Git provider profile",
  "authorPortal.distribution": "Intended distribution",
  "authorPortal.distribution.official": "Official catalog",
  "authorPortal.distribution.private": "Private catalog",
  "authorPortal.distribution.manual": "Manual installation",
  "authorPortal.descriptionLabel": "Short description",
  "authorPortal.publicJwks": "Author public JWKS",
  "authorPortal.publicJwksHint": "Only public author-managed signing keys. Never paste a private key.",
  "authorPortal.externalIssuer": "External licensing issuer URL",
  "authorPortal.acceptTerms": "I confirm the author terms and operating responsibilities.",
  "authorPortal.saveDraft": "Save draft",
  "authorPortal.updateDraft": "Update draft",
  "authorPortal.edit": "Edit",
  "authorPortal.cancelEdit": "Cancel editing",
  "authorPortal.myRequests": "My author requests",
  "authorPortal.status": "Status",
  "authorPortal.actions": "Actions",
  "authorPortal.submit": "Submit",
  "authorPortal.requestSaved": "Author request draft saved.",
  "authorPortal.requestUpdated": "Author request draft updated.",
  "authorPortal.requestSubmitted": "Author request submitted for review.",
  "authorPortal.noRequests": "No author requests yet. Save a draft above when you are ready.",
  "authorPortal.profile": "Author profile",
  "authorPortal.members": "Members",
  "authorPortal.membersDescription": "Roles and permissions apply only to the selected author identity.",
  "authorPortal.user": "User",
  "authorPortal.role": "Role",
  "authorPortal.userId": "Existing user ID",
  "authorPortal.addMember": "Add or update member",
  "authorPortal.memberSaved": "Author membership saved.",
  "authorPortal.noProfiles": "No approved author profile is available.",
  "authorPortal.noMembers": "No members are visible for this profile.",
  "authorPortal.role.owner": "Owner",
  "authorPortal.role.manager": "Manager",
  "authorPortal.role.developer": "Developer",
  "authorPortal.role.licensing": "Licensing manager",
  "authorPortal.role.viewer": "Viewer",
  "authorPortal.connectGitHub": "Connect GitHub",
  "authorPortal.gitSecurityHelp": "Use a fine-grained token limited to the required repositories and read-only contents. It is encrypted at rest and never displayed again.",
  "authorPortal.selectProfile": "Select author profile",
  "authorPortal.githubToken": "Fine-grained GitHub token",
  "authorPortal.connect": "Connect",
  "authorPortal.gitConnected": "GitHub account connected.",
  "authorPortal.gitConnections": "Git connections",
  "authorPortal.account": "Account",
  "authorPortal.repositories": "Repositories",
  "authorPortal.disconnect": "Disconnect",
  "authorPortal.gitDisconnected": "Git connection revoked and its stored credential removed.",
  "authorPortal.noGitConnections": "No Git provider is connected. Connect GitHub to access public or private repositories.",
  "authorPortal.createFromRepository": "Create application from repository",
  "authorPortal.privateRepoHelp": "Private repository contents are read only through the selected author-scoped connection.",
  "authorPortal.repository": "Repository",
  "authorPortal.selectRepository": "Select repository",
  "authorPortal.branch": "Branch",
  "authorPortal.manifestPath": "Manifest path",
  "authorPortal.validateManifest": "Validate manifest",
  "authorPortal.createApp": "Create app draft",
  "authorPortal.manifestChecked": "Repository manifest checked.",
  "authorPortal.manifestValid": "Manifest is valid and ready for an application draft.",
  "authorPortal.appDraftCreated": "Application draft created.",
  "authorPortal.repository.public": "Public repository",
  "authorPortal.repository.private": "Private repository",
  "authorPortal.repository.inaccessible": "Repository inaccessible",
  "authorPortal.application": "Application",
  "authorPortal.source": "Source",
  "authorPortal.runtime": "Runtime",
  "authorPortal.reviewRuntimePlan": "Review runtime and permissions",
  "authorPortal.applicationsDescription": "Review source, manifest, runtime policy and the next permitted workflow action.",
  "authorPortal.noApplications": "No applications yet. Validate a connected repository to create the first draft.",
  "authorPortal.appSubmitted": "Application submitted for review.",
  "authorPortal.appApproved": "Application approved.",
  "authorPortal.appRejected": "Application rejected.",
  "authorPortal.requestRuntime": "Request runtime",
  "authorPortal.runtimeRequested": "Runtime approval requested.",
  "authorPortal.approveRuntime": "Approve runtime",
  "authorPortal.runtimeApproved": "Runtime plan approved.",
  "authorPortal.submitCatalog": "Submit to catalog",
  "authorPortal.catalogSubmitted": "Application submitted to the official catalog.",
  "authorPortal.runtime.talpaversum_managed": "Talpaversum managed",
  "authorPortal.runtime.external": "External",
  "authorPortal.runtime.local_private": "Local private",
  "authorPortal.licensing.talpaversum_hosted": "Licensing is operated in an isolated Talpaversum-managed author namespace.",
  "authorPortal.licensing.trusted_self_hosted": "Licensing runs on your issuer. Its identity must chain to the approved author certificate.",
  "authorPortal.openLicensing": "Open licensing management",
  "authorPortal.issuerNotConfigured": "External issuer URL is not configured.",
  "authorPortal.privateLicensing": "Review local app licensing",
  "authorPortal.catalogDescription": "Official catalog submissions are available only to approved hosted or trusted self-hosted authors.",
  "authorPortal.startReview": "Start review",
  "authorPortal.reviewStarted": "Review started.",
  "authorPortal.approve": "Approve",
  "authorPortal.reject": "Reject",
  "authorPortal.requestChanges": "Request changes",
  "authorPortal.changesRequested": "Changes requested.",
  "authorPortal.publish": "Publish",
  "authorPortal.unpublish": "Unpublish",
  "authorPortal.catalogApproved": "Catalog submission approved.",
  "authorPortal.catalogRejected": "Catalog submission rejected.",
  "authorPortal.catalogPublished": "Catalog entry published.",
  "authorPortal.catalogUnpublished": "Catalog entry unpublished.",
  "authorPortal.noCatalogSubmissions": "No catalog submissions. Private applications are intentionally excluded from the official catalog.",
  "authorPortal.activity": "Audit and activity",
  "authorPortal.activityDescription": "Author-scoped security and workflow events.",
  "authorPortal.event": "Event",
  "authorPortal.transition": "Transition",
  "authorPortal.created": "Created",
  "authorPortal.noActivity": "No author workflow activity has been recorded yet.",
  "authorPortal.authorReviews": "Author reviews",
  "authorPortal.reviewDescription": "Review official requests and their trust, key custody and infrastructure implications.",
  "authorPortal.reviewNotes": "Review notes",
  "authorPortal.operatorOnly": "This section requires platform author-management permission.",
  "authorPortal.noReviews": "No author requests are waiting for operator action.",
  "authorPortal.authorApproved": "Author identity approved and provisioned.",
  "authorPortal.authorRejected": "Author request rejected.",
  "authorPortal.suspend": "Suspend",
  "authorPortal.revoke": "Revoke",
  "authorPortal.authorSuspended": "Author identity suspended.",
  "authorPortal.authorRevoked": "Author identity revoked.",
  "authorPortal.status.draft": "Draft",
  "authorPortal.status.submitted": "Submitted",
  "authorPortal.status.pending_review": "Pending review",
  "authorPortal.status.needs_changes": "Needs changes",
  "authorPortal.status.approved": "Approved",
  "authorPortal.status.rejected": "Rejected",
  "authorPortal.status.suspended": "Suspended",
  "authorPortal.status.revoked": "Revoked",
  "authorPortal.status.active": "Active",
  "authorPortal.status.ready_for_review": "Ready for review",
  "authorPortal.status.manifest_invalid": "Manifest invalid",
  "authorPortal.status.runtime_pending": "Runtime pending",
  "authorPortal.status.runtime_approved": "Runtime approved",
  "authorPortal.status.running": "Running",
  "authorPortal.status.published": "Published",
  "authorPortal.status.disabled": "Disabled",
  "authorPortal.status.unpublished": "Unpublished",
  "authorPortal.status.inaccessible": "Inaccessible",
  "authorPortal.event.author.request.created": "Author request created",
  "authorPortal.event.author.request.updated": "Author request updated",
  "authorPortal.event.author.request.submitted": "Author request submitted",
  "authorPortal.event.author.request.start_review": "Author review started",
  "authorPortal.event.author.request.request_changes": "Author changes requested",
  "authorPortal.event.author.request.approve": "Author approved",
  "authorPortal.event.author.request.reject": "Author rejected",
  "authorPortal.event.author.request.suspend": "Author suspended",
  "authorPortal.event.author.request.revoke": "Author revoked",
  "authorPortal.event.author.profile.updated": "Author profile updated",
  "authorPortal.event.author.membership.saved": "Author membership saved",
  "authorPortal.event.author.git.connected": "Git account connected",
  "authorPortal.event.author.git.disconnected": "Git account disconnected",
  "authorPortal.event.author.git.repositories.read": "Git repositories listed",
  "authorPortal.event.author.git.manifest.inspect": "Repository manifest inspected",
  "authorPortal.event.author.app.created_from_git": "Application created from Git",
  "authorPortal.event.author.app.submit": "Application submitted",
  "authorPortal.event.author.app.approve": "Application approved",
  "authorPortal.event.author.app.reject": "Application rejected",
  "authorPortal.event.author.app.request_runtime": "Runtime requested",
  "authorPortal.event.author.app.approve_runtime": "Runtime approved",
  "authorPortal.event.author.app.mark_running": "Application marked running",
  "authorPortal.event.author.app.disable": "Application disabled",
  "authorPortal.event.author.catalog.submitted": "Catalog submission created",
  "authorPortal.event.author.catalog.start_review": "Catalog review started",
  "authorPortal.event.author.catalog.request_changes": "Catalog changes requested",
  "authorPortal.event.author.catalog.approve": "Catalog submission approved",
  "authorPortal.event.author.catalog.reject": "Catalog submission rejected",
  "authorPortal.event.author.catalog.publish": "Catalog entry published",
  "authorPortal.event.author.catalog.unpublish": "Catalog entry unpublished",
};

const cs: Record<string, string> = {
  ...en,
  "nav.authorPortal": "Portál autora",
  "authorPortal.title": "Portál autora",
  "authorPortal.developerTools": "Vývojářské nástroje",
  "authorPortal.developerToolsDescription": "Vyvíjejte, instalujte a testujte soukromé aplikace bez schválení oficiálním registrem.",
  "authorPortal.privateApps": "Soukromé aplikace",
  "authorPortal.officialServices": "Volitelné oficiální služby",
  "authorPortal.officialServicesDescription": "Odkazy se zobrazí pouze tehdy, když instance příslušnou službu poskytuje a má ji nakonfigurovanou.",
  "authorPortal.registryAdministration": "Správa registru",
  "authorPortal.capabilityUnavailable": "Tato služba není na této instanci dostupná nebo nakonfigurovaná.",
  "authorPortal.available": "Dostupné",
  "authorPortal.unavailable": "Nedostupné",
  "authorPortal.openTool": "Otevřít nástroj",
  "authorPortal.activeAuthor": "Aktivní autor",
  "authorPortal.eyebrow": "Vývoj aplikací",
  "authorPortal.description": "Správa identit autorů, zdrojových repozitářů, aplikací, licencování a publikování do katalogu.",
  "authorPortal.requests": "Žádosti",
  "authorPortal.profiles": "Profily autorů",
  "authorPortal.applications": "Aplikace",
  "authorPortal.catalogSubmissions": "Žádosti o publikování",
  "authorPortal.private": "Soukromé",
  "authorPortal.official": "Oficiální důvěra",
  "authorPortal.emptyOverview": "Nejprve zvolte způsob vývoje. Soukromý vývoj zůstává lokální a nevyžaduje schválení registrem.",
  "authorPortal.become": "Stát se autorem",
  "authorPortal.becomeDescription": "Požádejte o oficiální identitu autora, nebo pokračujte lokálním postupem pro soukromé aplikace.",
  "authorPortal.mode": "Režim",
  "authorPortal.mode.talpaversum_hosted": "Hostováno na Talpaversum",
  "authorPortal.mode.talpaversum_hosted.description": "Talpaversum provozuje identitu v registru, runtime, podpisové klíče, licencování i katalog.",
  "authorPortal.mode.talpaversum_hosted.responsibility": "Vy spravujete zdrojový repozitář a metadata aplikace.",
  "authorPortal.mode.trusted_self_hosted": "Důvěryhodný self-hosting",
  "authorPortal.mode.trusted_self_hosted.description": "Oficiální registr zajišťuje důvěru, runtime, podpisový klíč a licenční issuer provozujete vy.",
  "authorPortal.mode.trusted_self_hosted.responsibility": "Odpovídáte za infrastrukturu, správu klíčů, aktualizace a dostupnost issueru.",
  "authorPortal.privateGuidance": "Soukromý self-hosted vývoj nevytváří oficiální žádost autora. Spusťte aplikaci lokálně, nastavte důvěryhodný origin a nainstalujte manifest nebo soukromý feed.",
  "authorPortal.configureOrigins": "Nastavit důvěryhodné originy",
  "authorPortal.installPrivateApp": "Nainstalovat soukromou aplikaci",
  "authorPortal.displayName": "Zobrazovaný název",
  "authorPortal.legalName": "Právní název nebo firma",
  "authorPortal.contactEmail": "Kontaktní e-mail",
  "authorPortal.website": "Web",
  "authorPortal.gitProfile": "Profil poskytovatele Git",
  "authorPortal.distribution": "Zamýšlená distribuce",
  "authorPortal.distribution.official": "Oficiální katalog",
  "authorPortal.distribution.private": "Soukromý katalog",
  "authorPortal.distribution.manual": "Ruční instalace",
  "authorPortal.descriptionLabel": "Krátký popis",
  "authorPortal.publicJwks": "Veřejný JWKS autora",
  "authorPortal.publicJwksHint": "Pouze veřejné podpisové klíče spravované autorem. Nikdy nevkládejte soukromý klíč.",
  "authorPortal.externalIssuer": "URL externího licenčního issueru",
  "authorPortal.acceptTerms": "Potvrzuji podmínky autora a provozní odpovědnost.",
  "authorPortal.saveDraft": "Uložit koncept",
  "authorPortal.updateDraft": "Aktualizovat koncept",
  "authorPortal.edit": "Upravit",
  "authorPortal.cancelEdit": "Zrušit úpravy",
  "authorPortal.myRequests": "Moje žádosti autora",
  "authorPortal.status": "Stav",
  "authorPortal.actions": "Akce",
  "authorPortal.submit": "Odeslat",
  "authorPortal.requestSaved": "Koncept žádosti byl uložen.",
  "authorPortal.requestUpdated": "Koncept žádosti byl aktualizován.",
  "authorPortal.requestSubmitted": "Žádost byla odeslána ke kontrole.",
  "authorPortal.noRequests": "Zatím zde nejsou žádné žádosti. Až budete připraveni, uložte koncept výše.",
  "authorPortal.profile": "Profil autora",
  "authorPortal.members": "Členové",
  "authorPortal.membersDescription": "Role a oprávnění platí pouze pro vybranou identitu autora.",
  "authorPortal.user": "Uživatel",
  "authorPortal.role": "Role",
  "authorPortal.userId": "ID existujícího uživatele",
  "authorPortal.addMember": "Přidat nebo upravit člena",
  "authorPortal.memberSaved": "Členství autora bylo uloženo.",
  "authorPortal.noProfiles": "Není k dispozici žádný schválený profil autora.",
  "authorPortal.noMembers": "Pro tento profil nejsou viditelní žádní členové.",
  "authorPortal.role.owner": "Vlastník",
  "authorPortal.role.manager": "Správce",
  "authorPortal.role.developer": "Vývojář",
  "authorPortal.role.licensing": "Správce licencí",
  "authorPortal.role.viewer": "Čtenář",
  "authorPortal.connectGitHub": "Připojit GitHub",
  "authorPortal.gitSecurityHelp": "Použijte fine-grained token omezený na potřebné repozitáře a čtení obsahu. Je šifrován v úložišti a již se znovu nezobrazí.",
  "authorPortal.selectProfile": "Vyberte profil autora",
  "authorPortal.githubToken": "Fine-grained GitHub token",
  "authorPortal.connect": "Připojit",
  "authorPortal.gitConnected": "Účet GitHub byl připojen.",
  "authorPortal.gitConnections": "Git připojení",
  "authorPortal.account": "Účet",
  "authorPortal.repositories": "Repozitáře",
  "authorPortal.disconnect": "Odpojit",
  "authorPortal.gitDisconnected": "Git připojení bylo zneplatněno a uložené přihlašovací údaje odstraněny.",
  "authorPortal.noGitConnections": "Není připojen žádný poskytovatel Git. Připojte GitHub pro přístup k veřejným i soukromým repozitářům.",
  "authorPortal.createFromRepository": "Vytvořit aplikaci z repozitáře",
  "authorPortal.privateRepoHelp": "Obsah soukromého repozitáře se čte pouze pomocí vybraného připojení omezeného na autora.",
  "authorPortal.repository": "Repozitář",
  "authorPortal.selectRepository": "Vyberte repozitář",
  "authorPortal.branch": "Větev",
  "authorPortal.manifestPath": "Cesta k manifestu",
  "authorPortal.validateManifest": "Ověřit manifest",
  "authorPortal.createApp": "Vytvořit koncept aplikace",
  "authorPortal.manifestChecked": "Manifest v repozitáři byl zkontrolován.",
  "authorPortal.manifestValid": "Manifest je platný a připravený k vytvoření konceptu aplikace.",
  "authorPortal.appDraftCreated": "Koncept aplikace byl vytvořen.",
  "authorPortal.repository.public": "Veřejný repozitář",
  "authorPortal.repository.private": "Soukromý repozitář",
  "authorPortal.repository.inaccessible": "Repozitář není dostupný",
  "authorPortal.application": "Aplikace",
  "authorPortal.source": "Zdroj",
  "authorPortal.runtime": "Runtime",
  "authorPortal.reviewRuntimePlan": "Zkontrolovat runtime a oprávnění",
  "authorPortal.applicationsDescription": "Zkontrolujte zdroj, manifest, pravidla runtime a další povolenou akci workflow.",
  "authorPortal.noApplications": "Zatím zde nejsou aplikace. Ověřením připojeného repozitáře vytvoříte první koncept.",
  "authorPortal.appSubmitted": "Aplikace byla odeslána ke kontrole.",
  "authorPortal.appApproved": "Aplikace byla schválena.",
  "authorPortal.appRejected": "Aplikace byla zamítnuta.",
  "authorPortal.requestRuntime": "Požádat o runtime",
  "authorPortal.runtimeRequested": "Bylo požádáno o schválení runtime.",
  "authorPortal.approveRuntime": "Schválit runtime",
  "authorPortal.runtimeApproved": "Plán runtime byl schválen.",
  "authorPortal.submitCatalog": "Odeslat do katalogu",
  "authorPortal.catalogSubmitted": "Aplikace byla odeslána do oficiálního katalogu.",
  "authorPortal.runtime.talpaversum_managed": "Spravuje Talpaversum",
  "authorPortal.runtime.external": "Externí",
  "authorPortal.runtime.local_private": "Lokální soukromý",
  "authorPortal.licensing.talpaversum_hosted": "Licencování je provozováno v izolovaném prostoru autora spravovaném Talpaversum.",
  "authorPortal.licensing.trusted_self_hosted": "Licencování běží na vašem issueru. Jeho identita musí navazovat na schválený certifikát autora.",
  "authorPortal.openLicensing": "Otevřít správu licencování",
  "authorPortal.issuerNotConfigured": "URL externího issueru není nastavena.",
  "authorPortal.privateLicensing": "Zkontrolovat lokální licencování aplikací",
  "authorPortal.catalogDescription": "Oficiální katalog je dostupný pouze schváleným hostovaným nebo důvěryhodným self-hosted autorům.",
  "authorPortal.startReview": "Zahájit kontrolu",
  "authorPortal.reviewStarted": "Kontrola byla zahájena.",
  "authorPortal.approve": "Schválit",
  "authorPortal.reject": "Zamítnout",
  "authorPortal.requestChanges": "Vyžádat změny",
  "authorPortal.changesRequested": "Byly vyžádány změny.",
  "authorPortal.publish": "Publikovat",
  "authorPortal.unpublish": "Stáhnout z publikace",
  "authorPortal.catalogApproved": "Žádost o publikování byla schválena.",
  "authorPortal.catalogRejected": "Žádost o publikování byla zamítnuta.",
  "authorPortal.catalogPublished": "Položka katalogu byla publikována.",
  "authorPortal.catalogUnpublished": "Položka katalogu byla stažena.",
  "authorPortal.noCatalogSubmissions": "Zatím zde nejsou žádné žádosti. Soukromé aplikace jsou z oficiálního katalogu záměrně vyloučeny.",
  "authorPortal.activity": "Audit a aktivita",
  "authorPortal.activityDescription": "Bezpečnostní události a workflow omezené na autora.",
  "authorPortal.event": "Událost",
  "authorPortal.transition": "Přechod",
  "authorPortal.created": "Vytvořeno",
  "authorPortal.noActivity": "Zatím nebyla zaznamenána žádná aktivita workflow autora.",
  "authorPortal.authorReviews": "Kontrola autorů",
  "authorPortal.reviewDescription": "Kontrola oficiálních žádostí a dopadů na důvěru, správu klíčů a infrastrukturu.",
  "authorPortal.reviewNotes": "Poznámky kontroly",
  "authorPortal.operatorOnly": "Tato část vyžaduje platformové oprávnění ke správě autorů.",
  "authorPortal.noReviews": "Žádná žádost autora nečeká na akci operátora.",
  "authorPortal.authorApproved": "Identita autora byla schválena a vytvořena.",
  "authorPortal.authorRejected": "Žádost autora byla zamítnuta.",
  "authorPortal.suspend": "Pozastavit",
  "authorPortal.revoke": "Odvolat",
  "authorPortal.authorSuspended": "Identita autora byla pozastavena.",
  "authorPortal.authorRevoked": "Identita autora byla odvolána.",
  "authorPortal.status.draft": "Koncept",
  "authorPortal.status.submitted": "Odesláno",
  "authorPortal.status.pending_review": "Čeká na kontrolu",
  "authorPortal.status.needs_changes": "Vyžaduje změny",
  "authorPortal.status.approved": "Schváleno",
  "authorPortal.status.rejected": "Zamítnuto",
  "authorPortal.status.suspended": "Pozastaveno",
  "authorPortal.status.revoked": "Odvoláno",
  "authorPortal.status.active": "Aktivní",
  "authorPortal.status.ready_for_review": "Připraveno ke kontrole",
  "authorPortal.status.manifest_invalid": "Neplatný manifest",
  "authorPortal.status.runtime_pending": "Runtime čeká na schválení",
  "authorPortal.status.runtime_approved": "Runtime schválen",
  "authorPortal.status.running": "Spuštěno",
  "authorPortal.status.published": "Publikováno",
  "authorPortal.status.disabled": "Zakázáno",
  "authorPortal.status.unpublished": "Staženo",
  "authorPortal.status.inaccessible": "Nedostupné",
  "authorPortal.event.author.request.created": "Žádost autora vytvořena",
  "authorPortal.event.author.request.updated": "Žádost autora aktualizována",
  "authorPortal.event.author.request.submitted": "Žádost autora odeslána",
  "authorPortal.event.author.request.start_review": "Kontrola autora zahájena",
  "authorPortal.event.author.request.request_changes": "Vyžádány změny žádosti autora",
  "authorPortal.event.author.request.approve": "Autor schválen",
  "authorPortal.event.author.request.reject": "Autor zamítnut",
  "authorPortal.event.author.request.suspend": "Autor pozastaven",
  "authorPortal.event.author.request.revoke": "Autor odvolán",
  "authorPortal.event.author.profile.updated": "Profil autora aktualizován",
  "authorPortal.event.author.membership.saved": "Členství autora uloženo",
  "authorPortal.event.author.git.connected": "Git účet připojen",
  "authorPortal.event.author.git.disconnected": "Git účet odpojen",
  "authorPortal.event.author.git.repositories.read": "Repozitáře Git načteny",
  "authorPortal.event.author.git.manifest.inspect": "Manifest repozitáře zkontrolován",
  "authorPortal.event.author.app.created_from_git": "Aplikace vytvořena z Gitu",
  "authorPortal.event.author.app.submit": "Aplikace odeslána",
  "authorPortal.event.author.app.approve": "Aplikace schválena",
  "authorPortal.event.author.app.reject": "Aplikace zamítnuta",
  "authorPortal.event.author.app.request_runtime": "Runtime vyžádán",
  "authorPortal.event.author.app.approve_runtime": "Runtime schválen",
  "authorPortal.event.author.app.mark_running": "Aplikace označena jako spuštěná",
  "authorPortal.event.author.app.disable": "Aplikace zakázána",
  "authorPortal.event.author.catalog.submitted": "Žádost katalogu vytvořena",
  "authorPortal.event.author.catalog.start_review": "Kontrola katalogu zahájena",
  "authorPortal.event.author.catalog.request_changes": "Vyžádány změny katalogu",
  "authorPortal.event.author.catalog.approve": "Žádost katalogu schválena",
  "authorPortal.event.author.catalog.reject": "Žádost katalogu zamítnuta",
  "authorPortal.event.author.catalog.publish": "Položka katalogu publikována",
  "authorPortal.event.author.catalog.unpublish": "Položka katalogu stažena",
};

const sk = { ...en, "authorPortal.developerTools": "Vývojárske nástroje", "authorPortal.developerToolsDescription": "Vyvíjajte, inštalujte a testujte súkromné aplikácie bez schválenia oficiálnym registrom.", "authorPortal.privateApps": "Súkromné aplikácie", "authorPortal.officialServices": "Voliteľné oficiálne služby", "authorPortal.officialServicesDescription": "Odkazy sa zobrazia iba vtedy, keď inštancia príslušnú službu poskytuje a má ju nakonfigurovanú.", "authorPortal.registryAdministration": "Správa registra", "authorPortal.capabilityUnavailable": "Táto služba nie je na tejto inštancii dostupná alebo nakonfigurovaná.", "authorPortal.available": "Dostupné", "authorPortal.unavailable": "Nedostupné", "authorPortal.openTool": "Otvoriť nástroj", "authorPortal.activeAuthor": "Aktívny autor" };
const de = { ...en, "authorPortal.developerTools": "Entwicklerwerkzeuge", "authorPortal.developerToolsDescription": "Private Anwendungen ohne Freigabe der offiziellen Registry entwickeln, installieren und testen.", "authorPortal.privateApps": "Private Anwendungen", "authorPortal.officialServices": "Optionale offizielle Dienste", "authorPortal.officialServicesDescription": "Links erscheinen nur, wenn diese Instanz den Dienst bereitstellt und konfiguriert hat.", "authorPortal.registryAdministration": "Registry-Verwaltung", "authorPortal.capabilityUnavailable": "Dieser Dienst ist auf dieser Instanz nicht verfügbar oder nicht konfiguriert.", "authorPortal.available": "Verfügbar", "authorPortal.unavailable": "Nicht verfügbar", "authorPortal.openTool": "Werkzeug öffnen", "authorPortal.activeAuthor": "Aktiver Autor" };
const fr = { ...en, "authorPortal.developerTools": "Outils de développement", "authorPortal.developerToolsDescription": "Développez, installez et testez des applications privées sans approbation du registre officiel.", "authorPortal.privateApps": "Applications privées", "authorPortal.officialServices": "Services officiels facultatifs", "authorPortal.officialServicesDescription": "Les liens apparaissent uniquement lorsque cette instance fournit et configure le service concerné.", "authorPortal.registryAdministration": "Administration du registre", "authorPortal.capabilityUnavailable": "Ce service n’est pas disponible ou configuré sur cette instance.", "authorPortal.available": "Disponible", "authorPortal.unavailable": "Indisponible", "authorPortal.openTool": "Ouvrir l’outil", "authorPortal.activeAuthor": "Auteur actif" };
const es = { ...en, "authorPortal.developerTools": "Herramientas de desarrollo", "authorPortal.developerToolsDescription": "Desarrolla, instala y prueba aplicaciones privadas sin la aprobación del registro oficial.", "authorPortal.privateApps": "Aplicaciones privadas", "authorPortal.officialServices": "Servicios oficiales opcionales", "authorPortal.officialServicesDescription": "Los enlaces solo aparecen cuando esta instancia ofrece y tiene configurado el servicio correspondiente.", "authorPortal.registryAdministration": "Administración del registro", "authorPortal.capabilityUnavailable": "Este servicio no está disponible o configurado en esta instancia.", "authorPortal.available": "Disponible", "authorPortal.unavailable": "No disponible", "authorPortal.openTool": "Abrir herramienta", "authorPortal.activeAuthor": "Autor activo" };

export const authorResources = {
  en,
  cs,
  sk,
  de,
  fr,
  es,
};
