const en: Record<string, string> = {
  "nav.authorPortal": "Author Portal",
  "authorPortal.title": "Author Portal",
  "authorPortal.developerTools": "Developer Tools",
  "authorPortal.developerToolsDescription": "Build, install and test private applications without official registry approval.",
  "authorPortal.privateApps": "Private applications",
  "authorPortal.officialServices": "Optional official services",
  "authorPortal.officialServicesDescription": "These links only appear when this instance provides and configures the relevant service.",
  "authorPortal.registryAdministration": "Registry Administration",
  "authorPortal.capabilityUnavailable": "This service is not available or configured on this instance.",
  "authorPortal.available": "Available",
  "authorPortal.unavailable": "Unavailable",
  "authorPortal.openTool": "Open tool",
  "authorPortal.activeAuthor": "Active author",
  "authorPortal.eyebrow": "Application authoring",
  "authorPortal.description": "Manage author identities, source repositories, applications, licensing and catalog submissions.",
  "authorPortal.requests": "Requests",
  "authorPortal.profiles": "Author profiles",
  "authorPortal.applications": "Applications",
  "authorPortal.catalogSubmissions": "Catalog submissions",
  "authorPortal.private": "Private",
  "authorPortal.official": "Official trust",
  "authorPortal.emptyOverview": "Choose an authoring mode to begin. Private development stays local and does not require registry approval.",
  "authorPortal.become": "Become an Author",
  "authorPortal.becomeDescription": "Request an official author identity, or follow the local workflow for private applications.",
  "authorPortal.mode": "Mode",
  "authorPortal.mode.talpaversum_hosted": "Hosted on Talpaversum",
  "authorPortal.mode.talpaversum_hosted.description": "Talpaversum operates the registry identity, runtime, signing keys, licensing and catalog workflow.",
  "authorPortal.mode.talpaversum_hosted.responsibility": "You maintain the source repository and application metadata.",
  "authorPortal.mode.trusted_self_hosted": "Trusted self-hosted",
  "authorPortal.mode.trusted_self_hosted.description": "The official Registry establishes trust, while you operate the runtime, signing key and licensing issuer.",
  "authorPortal.mode.trusted_self_hosted.responsibility": "You are responsible for infrastructure, key custody, updates and issuer availability.",
  "authorPortal.privateGuidance": "Private self-hosted development does not create an official author request. Run the app locally, configure its trusted origin, and install its manifest or private feed.",
  "authorPortal.configureOrigins": "Configure trusted origins",
  "authorPortal.installPrivateApp": "Install a private app",
  "authorPortal.displayName": "Display name",
  "authorPortal.legalName": "Legal or company name",
  "authorPortal.contactEmail": "Contact email",
  "authorPortal.website": "Website",
  "authorPortal.gitProfile": "Git provider profile",
  "authorPortal.distribution": "Intended distribution",
  "authorPortal.distribution.official": "Official catalog",
  "authorPortal.distribution.private": "Private catalog",
  "authorPortal.distribution.manual": "Manual installation",
  "authorPortal.descriptionLabel": "Short description",
  "authorPortal.publicJwks": "Author public JWKS",
  "authorPortal.publicJwksHint": "Only public author-managed signing keys. Never paste a private key.",
  "authorPortal.externalIssuer": "External licensing issuer URL",
  "authorPortal.acceptTerms": "I confirm the author terms and operating responsibilities.",
  "authorPortal.saveDraft": "Save draft",
  "authorPortal.updateDraft": "Update draft",
  "authorPortal.edit": "Edit",
  "authorPortal.cancelEdit": "Cancel editing",
  "authorPortal.myRequests": "My author requests",
  "authorPortal.status": "Status",
  "authorPortal.actions": "Actions",
  "authorPortal.submit": "Submit",
  "authorPortal.requestSaved": "Author request draft saved.",
  "authorPortal.requestUpdated": "Author request draft updated.",
  "authorPortal.requestSubmitted": "Author request submitted for review.",
  "authorPortal.noRequests": "No author requests yet. Save a draft above when you are ready.",
  "authorPortal.profile": "Author profile",
  "authorPortal.members": "Members",
  "authorPortal.membersDescription": "Roles and permissions apply only to the selected author identity.",
  "authorPortal.user": "User",
  "authorPortal.role": "Role",
  "authorPortal.userId": "Existing user ID",
  "authorPortal.addMember": "Add or update member",
  "authorPortal.memberSaved": "Author membership saved.",
  "authorPortal.noProfiles": "No approved author profile is available.",
  "authorPortal.noMembers": "No members are visible for this profile.",
  "authorPortal.role.owner": "Owner",
  "authorPortal.role.manager": "Manager",
  "authorPortal.role.developer": "Developer",
  "authorPortal.role.licensing": "Licensing manager",
  "authorPortal.role.viewer": "Viewer",
  "authorPortal.connectGitHub": "Connect GitHub",
  "authorPortal.gitSecurityHelp": "Use a fine-grained token limited to the required repositories and read-only contents. It is encrypted at rest and never displayed again.",
  "authorPortal.selectProfile": "Select author profile",
  "authorPortal.githubToken": "Fine-grained GitHub token",
  "authorPortal.connect": "Connect",
  "authorPortal.gitConnected": "GitHub account connected.",
  "authorPortal.gitConnections": "Git connections",
  "authorPortal.account": "Account",
  "authorPortal.repositories": "Repositories",
  "authorPortal.disconnect": "Disconnect",
  "authorPortal.gitDisconnected": "Git connection revoked and its stored credential removed.",
  "authorPortal.noGitConnections": "No Git provider is connected. Connect GitHub to access public or private repositories.",
  "authorPortal.createFromRepository": "Create application from repository",
  "authorPortal.privateRepoHelp": "Private repository contents are read only through the selected author-scoped connection.",
  "authorPortal.repository": "Repository",
  "authorPortal.selectRepository": "Select repository",
  "authorPortal.branch": "Branch",
  "authorPortal.manifestPath": "Manifest path",
  "authorPortal.validateManifest": "Validate manifest",
  "authorPortal.createApp": "Create app draft",
  "authorPortal.manifestChecked": "Repository manifest checked.",
  "authorPortal.manifestValid": "Manifest is valid and ready for an application draft.",
  "authorPortal.appDraftCreated": "Application draft created.",
  "authorPortal.repository.public": "Public repository",
  "authorPortal.repository.private": "Private repository",
  "authorPortal.repository.inaccessible": "Repository inaccessible",
  "authorPortal.application": "Application",
  "authorPortal.source": "Source",
  "authorPortal.runtime": "Runtime",
  "authorPortal.reviewRuntimePlan": "Review runtime and permissions",
  "authorPortal.applicationsDescription": "Review source, manifest, runtime policy and the next permitted workflow action.",
  "authorPortal.noApplications": "No applications yet. Validate a connected repository to create the first draft.",
  "authorPortal.appSubmitted": "Application submitted for review.",
  "authorPortal.appApproved": "Application approved.",
  "authorPortal.appRejected": "Application rejected.",
  "authorPortal.requestRuntime": "Request runtime",
  "authorPortal.runtimeRequested": "Runtime approval requested.",
  "authorPortal.approveRuntime": "Approve runtime",
  "authorPortal.runtimeApproved": "Runtime plan approved.",
  "authorPortal.submitCatalog": "Submit to catalog",
  "authorPortal.catalogSubmitted": "Application submitted to the official catalog.",
  "authorPortal.runtime.talpaversum_managed": "Talpaversum managed",
  "authorPortal.runtime.external": "External",
  "authorPortal.runtime.local_private": "Local private",
  "authorPortal.licensing.talpaversum_hosted": "Licensing is operated in an isolated Talpaversum-managed author namespace.",
  "authorPortal.licensing.trusted_self_hosted": "Licensing runs on your issuer. Its identity must chain to the approved author certificate.",
  "authorPortal.openLicensing": "Open licensing management",
  "authorPortal.issuerNotConfigured": "External issuer URL is not configured.",
  "authorPortal.privateLicensing": "Review local app licensing",
  "authorPortal.catalogDescription": "Official catalog submissions are available only to approved hosted or trusted self-hosted authors.",
  "authorPortal.startReview": "Start review",
  "authorPortal.reviewStarted": "Review started.",
  "authorPortal.approve": "Approve",
  "authorPortal.reject": "Reject",
  "authorPortal.requestChanges": "Request changes",
  "authorPortal.changesRequested": "Changes requested.",
  "authorPortal.publish": "Publish",
  "authorPortal.unpublish": "Unpublish",
  "authorPortal.catalogApproved": "Catalog submission approved.",
  "authorPortal.catalogRejected": "Catalog submission rejected.",
  "authorPortal.catalogPublished": "Catalog entry published.",
  "authorPortal.catalogUnpublished": "Catalog entry unpublished.",
  "authorPortal.noCatalogSubmissions": "No catalog submissions. Private applications are intentionally excluded from the official catalog.",
  "authorPortal.activity": "Audit and activity",
  "authorPortal.activityDescription": "Author-scoped security and workflow events.",
  "authorPortal.event": "Event",
  "authorPortal.transition": "Transition",
  "authorPortal.created": "Created",
  "authorPortal.noActivity": "No author workflow activity has been recorded yet.",
  "authorPortal.authorReviews": "Author reviews",
  "authorPortal.reviewDescription": "Review official requests and their trust, key custody and infrastructure implications.",
  "authorPortal.reviewNotes": "Review notes",
  "authorPortal.operatorOnly": "This section requires platform author-management permission.",
  "authorPortal.noReviews": "No author requests are waiting for operator action.",
  "authorPortal.authorApproved": "Author identity approved and provisioned.",
  "authorPortal.authorRejected": "Author request rejected.",
  "authorPortal.suspend": "Suspend",
  "authorPortal.revoke": "Revoke",
  "authorPortal.authorSuspended": "Author identity suspended.",
  "authorPortal.authorRevoked": "Author identity revoked.",
  "authorPortal.status.draft": "Draft",
  "authorPortal.status.submitted": "Submitted",
  "authorPortal.status.pending_review": "Pending review",
  "authorPortal.status.needs_changes": "Needs changes",
  "authorPortal.status.approved": "Approved",
  "authorPortal.status.rejected": "Rejected",
  "authorPortal.status.suspended": "Suspended",
  "authorPortal.status.revoked": "Revoked",
  "authorPortal.status.active": "Active",
  "authorPortal.status.ready_for_review": "Ready for review",
  "authorPortal.status.manifest_invalid": "Manifest invalid",
  "authorPortal.status.runtime_pending": "Runtime pending",
  "authorPortal.status.runtime_approved": "Runtime approved",
  "authorPortal.status.running": "Running",
  "authorPortal.status.published": "Published",
  "authorPortal.status.disabled": "Disabled",
  "authorPortal.status.unpublished": "Unpublished",
  "authorPortal.status.inaccessible": "Inaccessible",
  "authorPortal.event.author.request.created": "Author request created",
  "authorPortal.event.author.request.updated": "Author request updated",
  "authorPortal.event.author.request.submitted": "Author request submitted",
  "authorPortal.event.author.request.start_review": "Author review started",
  "authorPortal.event.author.request.request_changes": "Author changes requested",
  "authorPortal.event.author.request.approve": "Author approved",
  "authorPortal.event.author.request.reject": "Author rejected",
  "authorPortal.event.author.request.suspend": "Author suspended",
  "authorPortal.event.author.request.revoke": "Author revoked",
  "authorPortal.event.author.profile.updated": "Author profile updated",
  "authorPortal.event.author.membership.saved": "Author membership saved",
  "authorPortal.event.author.git.connected": "Git account connected",
  "authorPortal.event.author.git.disconnected": "Git account disconnected",
  "authorPortal.event.author.git.repositories.read": "Git repositories listed",
  "authorPortal.event.author.git.manifest.inspect": "Repository manifest inspected",
  "authorPortal.event.author.app.created_from_git": "Application created from Git",
  "authorPortal.event.author.app.submit": "Application submitted",
  "authorPortal.event.author.app.approve": "Application approved",
  "authorPortal.event.author.app.reject": "Application rejected",
  "authorPortal.event.author.app.request_runtime": "Runtime requested",
  "authorPortal.event.author.app.approve_runtime": "Runtime approved",
  "authorPortal.event.author.app.mark_running": "Application marked running",
  "authorPortal.event.author.app.disable": "Application disabled",
  "authorPortal.event.author.catalog.submitted": "Catalog submission created",
  "authorPortal.event.author.catalog.start_review": "Catalog review started",
  "authorPortal.event.author.catalog.request_changes": "Catalog changes requested",
  "authorPortal.event.author.catalog.approve": "Catalog submission approved",
  "authorPortal.event.author.catalog.reject": "Catalog submission rejected",
  "authorPortal.event.author.catalog.publish": "Catalog entry published",
  "authorPortal.event.author.catalog.unpublish": "Catalog entry unpublished",
  "developerProject.newProject": "New local project",
  "developerProject.projects": "Local projects",
  "developerProject.details": "Application details",
  "developerProject.displayName": "Project name",
  "developerProject.specification": "Application and manifest specification",
  "developerProject.runningApplication": "Running application",
  "developerProject.runningHint": "Start the application backend first, for example as a Docker container.",
  "developerProject.originUrl": "Application origin",
  "developerProject.sourceType": "Application source",
  "developerProject.manifest": "Manifest URL",
  "developerProject.feed": "Private feed URL",
  "developerProject.manifestUrl": "Manifest URL",
  "developerProject.feedUrl": "Private feed URL",
  "developerProject.createProject": "Create local project",
  "developerProject.saveChanges": "Save changes",
  "developerProject.created": "Local project created.",
  "developerProject.updated": "Local project updated.",
  "developerProject.connectivity": "Connectivity",
  "developerProject.testOrigin": "Test origin",
  "developerProject.connectivityChecked": "Connectivity test completed.",
  "developerProject.httpResult": "HTTP {{status}} in {{latency}} ms",
  "developerProject.connectionFailed": "Connection failed.",
  "developerProject.trustedOrigin": "Trusted origin",
  "developerProject.trustWarning": "Trusting this origin lets Core retrieve and install application resources from it. Only continue when you control or explicitly trust this origin.",
  "developerProject.confirmTrust": "I understand and trust this exact origin.",
  "developerProject.trustOrigin": "Add trusted origin",
  "developerProject.originTrusted": "Origin added to local trust.",
  "developerProject.validation": "Manifest or feed validation",
  "developerProject.validateSource": "Validate source",
  "developerProject.sourceValidated": "Source validation completed.",
  "developerProject.validSource": "The source and manifest are valid.",
  "developerProject.installation": "Installation",
  "developerProject.appId": "App ID",
  "developerProject.appName": "Application name",
  "developerProject.routes": "API routes",
  "developerProject.ui": "UI slug",
  "developerProject.licensing": "Licensing",
  "developerProject.required": "Required",
  "developerProject.notRequired": "Not required",
  "developerProject.install": "Install application",
  "developerProject.installed": "Private application installed.",
  "developerProject.result": "Result",
  "developerProject.localUnverified": "Local / unverified",
  "developerProject.openApplication": "Open application",
  "developerProject.appsManagement": "Apps Management",
  "developerProject.completePrevious": "Complete the previous step to continue.",
  "developerProject.state.active": "Current",
  "developerProject.state.complete": "Complete",
  "developerProject.state.locked": "Waiting",
  "developerProject.workspaceDescription": "Manage local application source, validation, deployment, runtime, updates and diagnostics without an official author identity.",
  "developerProject.addProject": "Add project",
  "developerProject.section.overview": "Overview",
  "developerProject.section.projects": "Projects",
  "developerProject.section.deployments": "Deployments",
  "developerProject.section.logs": "Logs",
  "developerProject.section.connections": "Connections",
  "developerProject.metric.projects": "Development projects",
  "developerProject.metric.running": "Running local apps",
  "developerProject.metric.updates": "Updates available",
  "developerProject.metric.invalid": "Invalid manifests",
  "developerProject.metric.runtimeErrors": "Runtime errors",
  "developerProject.recentProjects": "Recently changed projects",
  "developerProject.recentDeployments": "Recent deployments",
  "developerProject.sectionComingSoon": "This lifecycle view will use the same tenant-scoped project data.",
  "developerProject.source.manifest": "Manifest URL",
  "developerProject.source.feed": "Private feed",
  "developerProject.update.up_to_date": "Up to date",
  "developerProject.update.update_available": "Update available",
  "developerProject.update.validation_required": "Validation required",
  "developerProject.update.validation_failed": "Validation failed",
  "developerProject.update.deployment_required": "Deployment required",
  "developerProject.update.runtime_approval_required": "Runtime review required",
  "developerProject.update.deployment_failed": "Deployment failed",
  "developerProject.deploymentStatus": "Deployment",
  "developerProject.runtime": "Runtime",
  "developerProject.lastChanged": "Last changed",
  "developerProject.open": "Open",
  "developerProject.emptyProjects": "No development projects yet. Add a project to connect source, validate it, and manage its lifecycle.",
  "developerProject.notFound": "The project was not found in this tenant.",
  "developerProject.projectEntityDescription": "A project links source, configuration and deployments to the resulting installed application.",
  "developerProject.sourceRevision": "Source revision",
  "developerProject.validatedRevision": "Validated revision",
  "developerProject.deployedRevision": "Deployed revision",
  "developerProject.installedApp": "Installed app",
  "developerProject.wizardDescription": "Create a saved project draft and move through source, discovery, runtime, trust, validation and deployment one step at a time.",
  "developerProject.cancel": "Cancel",
  "developerProject.resumeDraft": "Resume a saved draft",
  "developerProject.wizard.sourceType": "Source type",
  "developerProject.wizard.sourceSelection": "Source selection",
  "developerProject.wizard.discovery": "Application discovery",
  "developerProject.wizard.details": "Application details",
  "developerProject.wizard.runtime": "Runtime configuration",
  "developerProject.wizard.connectivity": "Connectivity and trusted origin",
  "developerProject.wizard.validation": "Validation",
  "developerProject.wizard.review": "Deployment review",
  "developerProject.wizard.deploy": "Deploy",
  "developerProject.wizard.result": "Result",
  "developerProject.source.github": "GitHub",
  "developerProject.source.gitlab": "GitLab",
  "developerProject.source.git": "Git repository",
  "developerProject.source.local_workspace": "Local workspace",
  "developerProject.source.private_feed": "Private feed",
  "developerProject.connectionRequired": "Select or create a secure source connection in the next implementation phase.",
  "developerProject.manifestPath": "Manifest path",
  "developerProject.discoveryHint": "The platform searches the selected source and keeps the manifest path in the project draft.",
  "developerProject.runtimeType": "Runtime type",
  "developerProject.runtimeType.dockerfile": "Dockerfile",
  "developerProject.runtimeType.docker_compose": "Docker Compose",
  "developerProject.runtimeType.external_runtime": "External runtime",
  "developerProject.runtimeType.already_running_service": "Already running service",
  "developerProject.openProject": "Open project",
  "developerProject.back": "Back",
  "developerProject.next": "Next",
  "developerProject.saveExit": "Save and exit",
  "developerProject.connection": "Connection",
  "developerProject.selectConnection": "Select a verified connection",
  "developerProject.workspacePath": "Server workspace path",
  "developerProject.repository": "Repository",
  "developerProject.branch": "Branch or tag",
  "developerProject.connections": "Source connections",
  "developerProject.connectionsDescription": "Credentials and server workspace roots are tenant-scoped and stored separately from projects.",
  "developerProject.provider": "Provider",
  "developerProject.owner": "Owner or label",
  "developerProject.status": "Status",
  "developerProject.lastVerified": "Last verified",
  "developerProject.verifyConnection": "Verify",
  "developerProject.disconnect": "Disconnect",
  "developerProject.noConnections": "No source connections are configured for this tenant.",
  "developerProject.addConnection": "Add connection",
  "developerProject.authMethod": "Authentication method",
  "developerProject.installationId": "GitHub App installation ID",
  "developerProject.credential": "Credential",
  "developerProject.saveConnection": "Save connection",
  "developerProject.connectionSaved": "Connection saved.",
  "developerProject.secretHelp": "Secrets are encrypted, never returned to the browser, and removed when the connection is revoked.",
  "developerProject.connectionStatus.pending": "Pending",
  "developerProject.connectionStatus.verified": "Verified",
  "developerProject.connectionStatus.error": "Error",
  "developerProject.connectionStatus.revoked": "Revoked",
  "developerProject.authMethod.github_app": "GitHub App",
  "developerProject.authMethod.oauth": "OAuth",
  "developerProject.authMethod.project_token": "Project access token",
  "developerProject.authMethod.personal_token": "Personal access token",
  "developerProject.authMethod.https_credential": "HTTPS credential",
  "developerProject.authMethod.deploy_key": "SSH deploy key",
  "developerProject.authMethod.feed_credential": "Feed credential",
  "developerProject.sync": "Sync",
  "developerProject.changePreview": "Update change preview",
  "developerProject.changePreviewDescription": "Review manifest and security-significant runtime changes before validation or deployment.",
  "developerProject.manifestChanged": "Manifest changed",
  "developerProject.manifestUnchanged": "Manifest unchanged",
  "developerProject.runtimeChanged": "Runtime or security plan changed",
  "developerProject.runtimeUnchanged": "Runtime plan unchanged",
  "authorPortal.registryDescription": "Cryptographic author trust, certificates, keys, revocations and Registry audit.",
  "authorPortal.registryAuthors": "Registered authors",
  "authorPortal.registryExpiring": "Expiring certificates",
  "authorPortal.registryRevocations": "Revocations",
  "authorPortal.registryTrust": "Registry trust anchor",
  "authorPortal.registrySync": "Synchronize trust snapshot",
  "authorPortal.registryAudit": "Registry audit",
};

const cs: Record<string, string> = {
  ...en,
  "nav.authorPortal": "Portál autora",
  "authorPortal.title": "Portál autora",
  "authorPortal.developerTools": "Vývojářské nástroje",
  "authorPortal.developerToolsDescription": "Vyvíjejte, instalujte a testujte soukromé aplikace bez schválení oficiálním registrem.",
  "authorPortal.privateApps": "Soukromé aplikace",
  "authorPortal.officialServices": "Volitelné oficiální služby",
  "authorPortal.officialServicesDescription": "Odkazy se zobrazí pouze tehdy, když instance příslušnou službu poskytuje a má ji nakonfigurovanou.",
  "authorPortal.registryAdministration": "Správa registru",
  "authorPortal.capabilityUnavailable": "Tato služba není na této instanci dostupná nebo nakonfigurovaná.",
  "authorPortal.available": "Dostupné",
  "authorPortal.unavailable": "Nedostupné",
  "authorPortal.openTool": "Otevřít nástroj",
  "authorPortal.activeAuthor": "Aktivní autor",
  "authorPortal.eyebrow": "Vývoj aplikací",
  "authorPortal.description": "Správa identit autorů, zdrojových repozitářů, aplikací, licencování a publikování do katalogu.",
  "authorPortal.requests": "Žádosti",
  "authorPortal.profiles": "Profily autorů",
  "authorPortal.applications": "Aplikace",
  "authorPortal.catalogSubmissions": "Žádosti o publikování",
  "authorPortal.private": "Soukromé",
  "authorPortal.official": "Oficiální důvěra",
  "authorPortal.emptyOverview": "Nejprve zvolte způsob vývoje. Soukromý vývoj zůstává lokální a nevyžaduje schválení registrem.",
  "authorPortal.become": "Stát se autorem",
  "authorPortal.becomeDescription": "Požádejte o oficiální identitu autora, nebo pokračujte lokálním postupem pro soukromé aplikace.",
  "authorPortal.mode": "Režim",
  "authorPortal.mode.talpaversum_hosted": "Hostováno na Talpaversum",
  "authorPortal.mode.talpaversum_hosted.description": "Talpaversum provozuje identitu v registru, runtime, podpisové klíče, licencování i katalog.",
  "authorPortal.mode.talpaversum_hosted.responsibility": "Vy spravujete zdrojový repozitář a metadata aplikace.",
  "authorPortal.mode.trusted_self_hosted": "Důvěryhodný self-hosting",
  "authorPortal.mode.trusted_self_hosted.description": "Oficiální registr zajišťuje důvěru, runtime, podpisový klíč a licenční issuer provozujete vy.",
  "authorPortal.mode.trusted_self_hosted.responsibility": "Odpovídáte za infrastrukturu, správu klíčů, aktualizace a dostupnost issueru.",
  "authorPortal.privateGuidance": "Soukromý self-hosted vývoj nevytváří oficiální žádost autora. Spusťte aplikaci lokálně, nastavte důvěryhodný origin a nainstalujte manifest nebo soukromý feed.",
  "authorPortal.configureOrigins": "Nastavit důvěryhodné originy",
  "authorPortal.installPrivateApp": "Nainstalovat soukromou aplikaci",
  "authorPortal.displayName": "Zobrazovaný název",
  "authorPortal.legalName": "Právní název nebo firma",
  "authorPortal.contactEmail": "Kontaktní e-mail",
  "authorPortal.website": "Web",
  "authorPortal.gitProfile": "Profil poskytovatele Git",
  "authorPortal.distribution": "Zamýšlená distribuce",
  "authorPortal.distribution.official": "Oficiální katalog",
  "authorPortal.distribution.private": "Soukromý katalog",
  "authorPortal.distribution.manual": "Ruční instalace",
  "authorPortal.descriptionLabel": "Krátký popis",
  "authorPortal.publicJwks": "Veřejný JWKS autora",
  "authorPortal.publicJwksHint": "Pouze veřejné podpisové klíče spravované autorem. Nikdy nevkládejte soukromý klíč.",
  "authorPortal.externalIssuer": "URL externího licenčního issueru",
  "authorPortal.acceptTerms": "Potvrzuji podmínky autora a provozní odpovědnost.",
  "authorPortal.saveDraft": "Uložit koncept",
  "authorPortal.updateDraft": "Aktualizovat koncept",
  "authorPortal.edit": "Upravit",
  "authorPortal.cancelEdit": "Zrušit úpravy",
  "authorPortal.myRequests": "Moje žádosti autora",
  "authorPortal.status": "Stav",
  "authorPortal.actions": "Akce",
  "authorPortal.submit": "Odeslat",
  "authorPortal.requestSaved": "Koncept žádosti byl uložen.",
  "authorPortal.requestUpdated": "Koncept žádosti byl aktualizován.",
  "authorPortal.requestSubmitted": "Žádost byla odeslána ke kontrole.",
  "authorPortal.noRequests": "Zatím zde nejsou žádné žádosti. Až budete připraveni, uložte koncept výše.",
  "authorPortal.profile": "Profil autora",
  "authorPortal.members": "Členové",
  "authorPortal.membersDescription": "Role a oprávnění platí pouze pro vybranou identitu autora.",
  "authorPortal.user": "Uživatel",
  "authorPortal.role": "Role",
  "authorPortal.userId": "ID existujícího uživatele",
  "authorPortal.addMember": "Přidat nebo upravit člena",
  "authorPortal.memberSaved": "Členství autora bylo uloženo.",
  "authorPortal.noProfiles": "Není k dispozici žádný schválený profil autora.",
  "authorPortal.noMembers": "Pro tento profil nejsou viditelní žádní členové.",
  "authorPortal.role.owner": "Vlastník",
  "authorPortal.role.manager": "Správce",
  "authorPortal.role.developer": "Vývojář",
  "authorPortal.role.licensing": "Správce licencí",
  "authorPortal.role.viewer": "Čtenář",
  "authorPortal.connectGitHub": "Připojit GitHub",
  "authorPortal.gitSecurityHelp": "Použijte fine-grained token omezený na potřebné repozitáře a čtení obsahu. Je šifrován v úložišti a již se znovu nezobrazí.",
  "authorPortal.selectProfile": "Vyberte profil autora",
  "authorPortal.githubToken": "Fine-grained GitHub token",
  "authorPortal.connect": "Připojit",
  "authorPortal.gitConnected": "Účet GitHub byl připojen.",
  "authorPortal.gitConnections": "Git připojení",
  "authorPortal.account": "Účet",
  "authorPortal.repositories": "Repozitáře",
  "authorPortal.disconnect": "Odpojit",
  "authorPortal.gitDisconnected": "Git připojení bylo zneplatněno a uložené přihlašovací údaje odstraněny.",
  "authorPortal.noGitConnections": "Není připojen žádný poskytovatel Git. Připojte GitHub pro přístup k veřejným i soukromým repozitářům.",
  "authorPortal.createFromRepository": "Vytvořit aplikaci z repozitáře",
  "authorPortal.privateRepoHelp": "Obsah soukromého repozitáře se čte pouze pomocí vybraného připojení omezeného na autora.",
  "authorPortal.repository": "Repozitář",
  "authorPortal.selectRepository": "Vyberte repozitář",
  "authorPortal.branch": "Větev",
  "authorPortal.manifestPath": "Cesta k manifestu",
  "authorPortal.validateManifest": "Ověřit manifest",
  "authorPortal.createApp": "Vytvořit koncept aplikace",
  "authorPortal.manifestChecked": "Manifest v repozitáři byl zkontrolován.",
  "authorPortal.manifestValid": "Manifest je platný a připravený k vytvoření konceptu aplikace.",
  "authorPortal.appDraftCreated": "Koncept aplikace byl vytvořen.",
  "authorPortal.repository.public": "Veřejný repozitář",
  "authorPortal.repository.private": "Soukromý repozitář",
  "authorPortal.repository.inaccessible": "Repozitář není dostupný",
  "authorPortal.application": "Aplikace",
  "authorPortal.source": "Zdroj",
  "authorPortal.runtime": "Runtime",
  "authorPortal.reviewRuntimePlan": "Zkontrolovat runtime a oprávnění",
  "authorPortal.applicationsDescription": "Zkontrolujte zdroj, manifest, pravidla runtime a další povolenou akci workflow.",
  "authorPortal.noApplications": "Zatím zde nejsou aplikace. Ověřením připojeného repozitáře vytvoříte první koncept.",
  "authorPortal.appSubmitted": "Aplikace byla odeslána ke kontrole.",
  "authorPortal.appApproved": "Aplikace byla schválena.",
  "authorPortal.appRejected": "Aplikace byla zamítnuta.",
  "authorPortal.requestRuntime": "Požádat o runtime",
  "authorPortal.runtimeRequested": "Bylo požádáno o schválení runtime.",
  "authorPortal.approveRuntime": "Schválit runtime",
  "authorPortal.runtimeApproved": "Plán runtime byl schválen.",
  "authorPortal.submitCatalog": "Odeslat do katalogu",
  "authorPortal.catalogSubmitted": "Aplikace byla odeslána do oficiálního katalogu.",
  "authorPortal.runtime.talpaversum_managed": "Spravuje Talpaversum",
  "authorPortal.runtime.external": "Externí",
  "authorPortal.runtime.local_private": "Lokální soukromý",
  "authorPortal.licensing.talpaversum_hosted": "Licencování je provozováno v izolovaném prostoru autora spravovaném Talpaversum.",
  "authorPortal.licensing.trusted_self_hosted": "Licencování běží na vašem issueru. Jeho identita musí navazovat na schválený certifikát autora.",
  "authorPortal.openLicensing": "Otevřít správu licencování",
  "authorPortal.issuerNotConfigured": "URL externího issueru není nastavena.",
  "authorPortal.privateLicensing": "Zkontrolovat lokální licencování aplikací",
  "authorPortal.catalogDescription": "Oficiální katalog je dostupný pouze schváleným hostovaným nebo důvěryhodným self-hosted autorům.",
  "authorPortal.startReview": "Zahájit kontrolu",
  "authorPortal.reviewStarted": "Kontrola byla zahájena.",
  "authorPortal.approve": "Schválit",
  "authorPortal.reject": "Zamítnout",
  "authorPortal.requestChanges": "Vyžádat změny",
  "authorPortal.changesRequested": "Byly vyžádány změny.",
  "authorPortal.publish": "Publikovat",
  "authorPortal.unpublish": "Stáhnout z publikace",
  "authorPortal.catalogApproved": "Žádost o publikování byla schválena.",
  "authorPortal.catalogRejected": "Žádost o publikování byla zamítnuta.",
  "authorPortal.catalogPublished": "Položka katalogu byla publikována.",
  "authorPortal.catalogUnpublished": "Položka katalogu byla stažena.",
  "authorPortal.noCatalogSubmissions": "Zatím zde nejsou žádné žádosti. Soukromé aplikace jsou z oficiálního katalogu záměrně vyloučeny.",
  "authorPortal.activity": "Audit a aktivita",
  "authorPortal.activityDescription": "Bezpečnostní události a workflow omezené na autora.",
  "authorPortal.event": "Událost",
  "authorPortal.transition": "Přechod",
  "authorPortal.created": "Vytvořeno",
  "authorPortal.noActivity": "Zatím nebyla zaznamenána žádná aktivita workflow autora.",
  "authorPortal.authorReviews": "Kontrola autorů",
  "authorPortal.reviewDescription": "Kontrola oficiálních žádostí a dopadů na důvěru, správu klíčů a infrastrukturu.",
  "authorPortal.reviewNotes": "Poznámky kontroly",
  "authorPortal.operatorOnly": "Tato část vyžaduje platformové oprávnění ke správě autorů.",
  "authorPortal.noReviews": "Žádná žádost autora nečeká na akci operátora.",
  "authorPortal.authorApproved": "Identita autora byla schválena a vytvořena.",
  "authorPortal.authorRejected": "Žádost autora byla zamítnuta.",
  "authorPortal.suspend": "Pozastavit",
  "authorPortal.revoke": "Odvolat",
  "authorPortal.authorSuspended": "Identita autora byla pozastavena.",
  "authorPortal.authorRevoked": "Identita autora byla odvolána.",
  "authorPortal.status.draft": "Koncept",
  "authorPortal.status.submitted": "Odesláno",
  "authorPortal.status.pending_review": "Čeká na kontrolu",
  "authorPortal.status.needs_changes": "Vyžaduje změny",
  "authorPortal.status.approved": "Schváleno",
  "authorPortal.status.rejected": "Zamítnuto",
  "authorPortal.status.suspended": "Pozastaveno",
  "authorPortal.status.revoked": "Odvoláno",
  "authorPortal.status.active": "Aktivní",
  "authorPortal.status.ready_for_review": "Připraveno ke kontrole",
  "authorPortal.status.manifest_invalid": "Neplatný manifest",
  "authorPortal.status.runtime_pending": "Runtime čeká na schválení",
  "authorPortal.status.runtime_approved": "Runtime schválen",
  "authorPortal.status.running": "Spuštěno",
  "authorPortal.status.published": "Publikováno",
  "authorPortal.status.disabled": "Zakázáno",
  "authorPortal.status.unpublished": "Staženo",
  "authorPortal.status.inaccessible": "Nedostupné",
  "authorPortal.event.author.request.created": "Žádost autora vytvořena",
  "authorPortal.event.author.request.updated": "Žádost autora aktualizována",
  "authorPortal.event.author.request.submitted": "Žádost autora odeslána",
  "authorPortal.event.author.request.start_review": "Kontrola autora zahájena",
  "authorPortal.event.author.request.request_changes": "Vyžádány změny žádosti autora",
  "authorPortal.event.author.request.approve": "Autor schválen",
  "authorPortal.event.author.request.reject": "Autor zamítnut",
  "authorPortal.event.author.request.suspend": "Autor pozastaven",
  "authorPortal.event.author.request.revoke": "Autor odvolán",
  "authorPortal.event.author.profile.updated": "Profil autora aktualizován",
  "authorPortal.event.author.membership.saved": "Členství autora uloženo",
  "authorPortal.event.author.git.connected": "Git účet připojen",
  "authorPortal.event.author.git.disconnected": "Git účet odpojen",
  "authorPortal.event.author.git.repositories.read": "Repozitáře Git načteny",
  "authorPortal.event.author.git.manifest.inspect": "Manifest repozitáře zkontrolován",
  "authorPortal.event.author.app.created_from_git": "Aplikace vytvořena z Gitu",
  "authorPortal.event.author.app.submit": "Aplikace odeslána",
  "authorPortal.event.author.app.approve": "Aplikace schválena",
  "authorPortal.event.author.app.reject": "Aplikace zamítnuta",
  "authorPortal.event.author.app.request_runtime": "Runtime vyžádán",
  "authorPortal.event.author.app.approve_runtime": "Runtime schválen",
  "authorPortal.event.author.app.mark_running": "Aplikace označena jako spuštěná",
  "authorPortal.event.author.app.disable": "Aplikace zakázána",
  "authorPortal.event.author.catalog.submitted": "Žádost katalogu vytvořena",
  "authorPortal.event.author.catalog.start_review": "Kontrola katalogu zahájena",
  "authorPortal.event.author.catalog.request_changes": "Vyžádány změny katalogu",
  "authorPortal.event.author.catalog.approve": "Žádost katalogu schválena",
  "authorPortal.event.author.catalog.reject": "Žádost katalogu zamítnuta",
  "authorPortal.event.author.catalog.publish": "Položka katalogu publikována",
  "authorPortal.event.author.catalog.unpublish": "Položka katalogu stažena",
  "developerProject.newProject": "Nový lokální projekt",
  "developerProject.projects": "Lokální projekty",
  "developerProject.details": "Údaje aplikace",
  "developerProject.displayName": "Název projektu",
  "developerProject.specification": "Specifikace aplikace a manifestu",
  "developerProject.runningApplication": "Spuštěná aplikace",
  "developerProject.runningHint": "Nejprve spusťte backend aplikace, například jako Docker kontejner.",
  "developerProject.originUrl": "Origin aplikace",
  "developerProject.sourceType": "Zdroj aplikace",
  "developerProject.manifest": "URL manifestu",
  "developerProject.feed": "URL soukromého feedu",
  "developerProject.manifestUrl": "URL manifestu",
  "developerProject.feedUrl": "URL soukromého feedu",
  "developerProject.createProject": "Vytvořit lokální projekt",
  "developerProject.saveChanges": "Uložit změny",
  "developerProject.created": "Lokální projekt byl vytvořen.",
  "developerProject.updated": "Lokální projekt byl upraven.",
  "developerProject.connectivity": "Konektivita",
  "developerProject.testOrigin": "Otestovat origin",
  "developerProject.connectivityChecked": "Test konektivity byl dokončen.",
  "developerProject.httpResult": "HTTP {{status}} za {{latency}} ms",
  "developerProject.connectionFailed": "Připojení selhalo.",
  "developerProject.trustedOrigin": "Důvěryhodný origin",
  "developerProject.trustWarning": "Důvěra tomuto originu dovolí Core načítat a instalovat zdroje aplikace. Pokračujte pouze tehdy, pokud origin ovládáte nebo mu výslovně důvěřujete.",
  "developerProject.confirmTrust": "Rozumím riziku a důvěřuji přesně tomuto originu.",
  "developerProject.trustOrigin": "Přidat důvěryhodný origin",
  "developerProject.originTrusted": "Origin byl přidán do lokální důvěry.",
  "developerProject.validation": "Validace manifestu nebo feedu",
  "developerProject.validateSource": "Validovat zdroj",
  "developerProject.sourceValidated": "Validace zdroje byla dokončena.",
  "developerProject.validSource": "Zdroj i manifest jsou platné.",
  "developerProject.installation": "Instalace",
  "developerProject.appId": "ID aplikace",
  "developerProject.appName": "Název aplikace",
  "developerProject.routes": "API routes",
  "developerProject.ui": "UI slug",
  "developerProject.licensing": "Licencování",
  "developerProject.required": "Vyžadováno",
  "developerProject.notRequired": "Není vyžadováno",
  "developerProject.install": "Nainstalovat aplikaci",
  "developerProject.installed": "Soukromá aplikace byla nainstalována.",
  "developerProject.result": "Výsledek",
  "developerProject.localUnverified": "Lokální / neověřená",
  "developerProject.openApplication": "Otevřít aplikaci",
  "developerProject.appsManagement": "Technická správa aplikací",
  "developerProject.completePrevious": "Pro pokračování dokončete předchozí krok.",
  "developerProject.state.active": "Aktuální",
  "developerProject.state.complete": "Hotovo",
  "developerProject.state.locked": "Čeká",
  "developerProject.workspaceDescription": "Správa zdroje, validace, nasazení, runtime, aktualizací a diagnostiky lokálních aplikací bez oficiální identity autora.",
  "developerProject.addProject": "Přidat projekt",
  "developerProject.section.overview": "Přehled",
  "developerProject.section.projects": "Projekty",
  "developerProject.section.deployments": "Nasazení",
  "developerProject.section.logs": "Logy",
  "developerProject.section.connections": "Připojení",
  "developerProject.metric.projects": "Vývojové projekty",
  "developerProject.metric.running": "Běžící lokální aplikace",
  "developerProject.metric.updates": "Dostupné aktualizace",
  "developerProject.metric.invalid": "Neplatné manifesty",
  "developerProject.metric.runtimeErrors": "Chyby runtime",
  "developerProject.recentProjects": "Naposledy změněné projekty",
  "developerProject.recentDeployments": "Poslední nasazení",
  "developerProject.sectionComingSoon": "Tento lifecycle pohled používá stejná projektová data omezená na tenant.",
  "developerProject.source.manifest": "URL manifestu",
  "developerProject.source.feed": "Soukromý feed",
  "developerProject.update.up_to_date": "Aktuální",
  "developerProject.update.update_available": "Dostupná aktualizace",
  "developerProject.update.validation_required": "Vyžaduje validaci",
  "developerProject.update.validation_failed": "Validace selhala",
  "developerProject.update.deployment_required": "Vyžaduje nasazení",
  "developerProject.update.runtime_approval_required": "Vyžaduje kontrolu runtime",
  "developerProject.update.deployment_failed": "Nasazení selhalo",
  "developerProject.deploymentStatus": "Nasazení",
  "developerProject.runtime": "Runtime",
  "developerProject.lastChanged": "Poslední změna",
  "developerProject.open": "Otevřít",
  "developerProject.emptyProjects": "Zatím nejsou žádné vývojové projekty. Přidejte projekt, připojte zdroj a spravujte celý jeho lifecycle.",
  "developerProject.notFound": "Projekt nebyl v tomto tenantu nalezen.",
  "developerProject.projectEntityDescription": "Projekt propojuje zdroj, konfiguraci a nasazení s výslednou nainstalovanou aplikací.",
  "developerProject.sourceRevision": "Revision zdroje",
  "developerProject.validatedRevision": "Validovaná revision",
  "developerProject.deployedRevision": "Nasazená revision",
  "developerProject.installedApp": "Nainstalovaná aplikace",
  "developerProject.wizardDescription": "Vytvořte uložený draft projektu a postupujte po jednotlivých krocích přes zdroj, nalezení aplikace, runtime, důvěru, validaci a nasazení.",
  "developerProject.cancel": "Zrušit",
  "developerProject.resumeDraft": "Pokračovat v uloženém draftu",
  "developerProject.wizard.sourceType": "Typ zdroje",
  "developerProject.wizard.sourceSelection": "Výběr zdroje",
  "developerProject.wizard.discovery": "Nalezení aplikace",
  "developerProject.wizard.details": "Údaje aplikace",
  "developerProject.wizard.runtime": "Konfigurace runtime",
  "developerProject.wizard.connectivity": "Konektivita a důvěryhodný origin",
  "developerProject.wizard.validation": "Validace",
  "developerProject.wizard.review": "Kontrola nasazení",
  "developerProject.wizard.deploy": "Nasazení",
  "developerProject.wizard.result": "Výsledek",
  "developerProject.source.github": "GitHub",
  "developerProject.source.gitlab": "GitLab",
  "developerProject.source.git": "Git repozitář",
  "developerProject.source.local_workspace": "Lokální workspace",
  "developerProject.source.private_feed": "Soukromý feed",
  "developerProject.connectionRequired": "Vyberte nebo vytvořte bezpečné připojení zdroje v následující implementační fázi.",
  "developerProject.manifestPath": "Cesta k manifestu",
  "developerProject.discoveryHint": "Platforma prohledá vybraný zdroj a uloží cestu k manifestu do draftu projektu.",
  "developerProject.runtimeType": "Typ runtime",
  "developerProject.runtimeType.dockerfile": "Dockerfile",
  "developerProject.runtimeType.docker_compose": "Docker Compose",
  "developerProject.runtimeType.external_runtime": "Externí runtime",
  "developerProject.runtimeType.already_running_service": "Již běžící služba",
  "developerProject.openProject": "Otevřít projekt",
  "developerProject.back": "Zpět",
  "developerProject.next": "Další",
  "developerProject.saveExit": "Uložit a odejít",
  "developerProject.connection": "Připojení",
  "developerProject.selectConnection": "Vyberte ověřené připojení",
  "developerProject.workspacePath": "Cesta workspace na serveru",
  "developerProject.repository": "Repozitář",
  "developerProject.branch": "Branch nebo tag",
  "developerProject.connections": "Připojení zdrojů",
  "developerProject.connectionsDescription": "Credentials a serverové workspace roots jsou omezené na tenant a uložené odděleně od projektů.",
  "developerProject.provider": "Provider",
  "developerProject.owner": "Vlastník nebo název",
  "developerProject.status": "Stav",
  "developerProject.lastVerified": "Naposledy ověřeno",
  "developerProject.verifyConnection": "Ověřit",
  "developerProject.disconnect": "Odpojit",
  "developerProject.noConnections": "Pro tento tenant nejsou nakonfigurována žádná připojení zdrojů.",
  "developerProject.addConnection": "Přidat připojení",
  "developerProject.authMethod": "Způsob autentizace",
  "developerProject.installationId": "ID instalace GitHub App",
  "developerProject.credential": "Credential",
  "developerProject.saveConnection": "Uložit připojení",
  "developerProject.connectionSaved": "Připojení bylo uloženo.",
  "developerProject.secretHelp": "Secrets jsou šifrované, nikdy se nevracejí do prohlížeče a při revokaci se odstraní.",
  "developerProject.connectionStatus.pending": "Čeká",
  "developerProject.connectionStatus.verified": "Ověřeno",
  "developerProject.connectionStatus.error": "Chyba",
  "developerProject.connectionStatus.revoked": "Revokováno",
  "developerProject.authMethod.github_app": "GitHub App",
  "developerProject.authMethod.oauth": "OAuth",
  "developerProject.authMethod.project_token": "Project access token",
  "developerProject.authMethod.personal_token": "Personal access token",
  "developerProject.authMethod.https_credential": "HTTPS credential",
  "developerProject.authMethod.deploy_key": "SSH deploy key",
  "developerProject.authMethod.feed_credential": "Credential feedu",
  "developerProject.sync": "Synchronizovat",
  "developerProject.changePreview": "Náhled změn aktualizace",
  "developerProject.changePreviewDescription": "Před validací nebo nasazením zkontrolujte změny manifestu a bezpečnostně významné části runtime.",
  "developerProject.manifestChanged": "Manifest se změnil",
  "developerProject.manifestUnchanged": "Manifest se nezměnil",
  "developerProject.runtimeChanged": "Runtime nebo bezpečnostní plán se změnil",
  "developerProject.runtimeUnchanged": "Runtime plán se nezměnil",
  "authorPortal.registryDescription": "Kryptografická důvěra autorů, certifikáty, klíče, revokace a audit registru.",
  "authorPortal.registryAuthors": "Registrovaní autoři",
  "authorPortal.registryExpiring": "Končící certifikáty",
  "authorPortal.registryRevocations": "Revokace",
  "authorPortal.registryTrust": "Kořen důvěry registru",
  "authorPortal.registrySync": "Synchronizovat snapshot důvěry",
  "authorPortal.registryAudit": "Audit registru",
};

const sk = { ...en, "authorPortal.developerTools": "Vývojárske nástroje", "authorPortal.developerToolsDescription": "Vyvíjajte, inštalujte a testujte súkromné aplikácie bez schválenia oficiálnym registrom.", "authorPortal.privateApps": "Súkromné aplikácie", "authorPortal.officialServices": "Voliteľné oficiálne služby", "authorPortal.officialServicesDescription": "Odkazy sa zobrazia iba vtedy, keď inštancia príslušnú službu poskytuje a má ju nakonfigurovanú.", "authorPortal.registryAdministration": "Správa registra", "authorPortal.capabilityUnavailable": "Táto služba nie je na tejto inštancii dostupná alebo nakonfigurovaná.", "authorPortal.available": "Dostupné", "authorPortal.unavailable": "Nedostupné", "authorPortal.openTool": "Otvoriť nástroj", "authorPortal.activeAuthor": "Aktívny autor" };
const de = { ...en, "authorPortal.developerTools": "Entwicklerwerkzeuge", "authorPortal.developerToolsDescription": "Private Anwendungen ohne Freigabe der offiziellen Registry entwickeln, installieren und testen.", "authorPortal.privateApps": "Private Anwendungen", "authorPortal.officialServices": "Optionale offizielle Dienste", "authorPortal.officialServicesDescription": "Links erscheinen nur, wenn diese Instanz den Dienst bereitstellt und konfiguriert hat.", "authorPortal.registryAdministration": "Registry-Verwaltung", "authorPortal.capabilityUnavailable": "Dieser Dienst ist auf dieser Instanz nicht verfügbar oder nicht konfiguriert.", "authorPortal.available": "Verfügbar", "authorPortal.unavailable": "Nicht verfügbar", "authorPortal.openTool": "Werkzeug öffnen", "authorPortal.activeAuthor": "Aktiver Autor" };
const fr = { ...en, "authorPortal.developerTools": "Outils de développement", "authorPortal.developerToolsDescription": "Développez, installez et testez des applications privées sans approbation du registre officiel.", "authorPortal.privateApps": "Applications privées", "authorPortal.officialServices": "Services officiels facultatifs", "authorPortal.officialServicesDescription": "Les liens apparaissent uniquement lorsque cette instance fournit et configure le service concerné.", "authorPortal.registryAdministration": "Administration du registre", "authorPortal.capabilityUnavailable": "Ce service n’est pas disponible ou configuré sur cette instance.", "authorPortal.available": "Disponible", "authorPortal.unavailable": "Indisponible", "authorPortal.openTool": "Ouvrir l’outil", "authorPortal.activeAuthor": "Auteur actif" };
const es = { ...en, "authorPortal.developerTools": "Herramientas de desarrollo", "authorPortal.developerToolsDescription": "Desarrolla, instala y prueba aplicaciones privadas sin la aprobación del registro oficial.", "authorPortal.privateApps": "Aplicaciones privadas", "authorPortal.officialServices": "Servicios oficiales opcionales", "authorPortal.officialServicesDescription": "Los enlaces solo aparecen cuando esta instancia ofrece y tiene configurado el servicio correspondiente.", "authorPortal.registryAdministration": "Administración del registro", "authorPortal.capabilityUnavailable": "Este servicio no está disponible o configurado en esta instancia.", "authorPortal.available": "Disponible", "authorPortal.unavailable": "No disponible", "authorPortal.openTool": "Abrir herramienta", "authorPortal.activeAuthor": "Autor activo" };

export const authorResources = {
  en,
  cs,
  sk,
  de,
  fr,
  es,
};
