const en = {
  "config.configuration": "Configuration", "config.never": "Never", "config.active": "active", "config.disabled": "disabled",
  "authors.jwksRequired": "JWKS must contain at least one public key.", "authors.title": "Application authors", "authors.authors": "Authors",
  "authors.rootKeys": "Root keys", "authors.revocations": "Revocations", "authors.trustSync": "Trust sync", "authors.current": "Current", "authors.missing": "Missing",
  "authors.registryTrust": "Author registry trust", "authors.noTrustSnapshot": "No trust snapshot has been synchronized for the configured registry.",
  "authors.syncing": "Syncing...", "authors.syncTrust": "Sync trust", "authors.lastSynchronized": "Last synchronized", "authors.synchronizedBy": "Synchronized by",
  "authors.registry": "Registry", "authors.description": "Registry-backed author identities and their public signing keys.", "authors.count": "{{count}} authors",
  "authors.onboardAuthor": "Onboard author", "authors.displayName": "Display name", "authors.publicJwks": "Public JWKS", "authors.certificateTtl": "Certificate TTL",
  "authors.onboarding": "Onboarding...", "authors.onboard": "Onboard", "authors.loading": "Loading authors...", "authors.rootKey": "Root key",
  "authors.publicKeys": "Public keys", "authors.updated": "Updated", "authors.notReported": "Not reported", "authors.replacementJwks": "Replacement public JWKS",
  "authors.rotating": "Rotating...", "authors.rotateKeys": "Rotate keys", "authors.none": "No authors onboarded.", "authors.author": "Author", "authors.action": "Action",
  "authors.onboarded": "{{name}} was onboarded.", "authors.rotated": "{{name}} signing keys were rotated.", "authors.synchronized": "Author registry trust data was synchronized.",
  "tenant.title": "Tenant configuration", "tenant.description": "Tenant-local settings for identity, app access, and license selection.",
  "tenant.detailsUpdated": "Tenant details were updated.", "tenant.privilegeExists": "This user already has that tenant privilege.",
  "tenant.privilegeAdded": "Tenant privilege was added.", "tenant.privilegeRemoved": "Tenant privilege was removed.",
  "tenant.installedApps": "Installed apps", "tenant.licenseRequired": "License required", "tenant.users": "Users", "tenant.mode": "Tenant mode",
  "tenant.fallbackName": "Tenant", "tenant.noPrimaryDomain": "No primary domain", "tenant.details": "Tenant details",
  "tenant.detailsDescription": "Edit the tenant display name and primary domain used for tenant resolution.", "tenant.name": "Tenant name", "tenant.primaryDomain": "Primary domain",
  "tenant.save": "Save tenant", "tenant.dataPolicy": "Data policy", "tenant.dataPolicyDescription": "Tenant-level retention and isolation policy summary.",
  "tenant.operationalContacts": "Operational contacts", "tenant.operationalContactsDescription": "People and addresses responsible for tenant operations.",
  "tenant.usersRoles": "Users and privileges", "tenant.usersRolesDescription": "Manage tenant-scoped privilege grants for users already known to the platform.",
  "tenant.usersCount": "{{count}} users", "tenant.user": "User", "tenant.privilege": "Tenant privilege", "tenant.selectPrivilege": "Select tenant privilege",
  "tenant.addPrivilege": "Add privilege", "tenant.noUsers": "No tenant users yet. A platform administrator can create users and grant the first tenant privilege from Platform settings.",
  "tenant.appsLicenses": "Apps and licenses", "tenant.appsLicensesDescription": "App installation, catalog sync, feed publishing, and license selection are managed from Applications.",
  "tenant.activeElsewhere": "active elsewhere", "tenant.installedAppsDescription": "Runtime apps known to this Core instance.", "tenant.licenseApps": "License-required apps",
  "tenant.licenseAppsDescription": "Catalog entries that need tenant license selection.", "tenant.feedPublishing": "Feed publishing", "tenant.adminGated": "admin gated",
  "tenant.feedPublishingDescription": "Only installed apps can be published to this instance feed.", "tenant.auditContext": "Audit context",
  "tenant.auditDescription": "Tenant-scoped audit search and review will belong here once audit query APIs are available.", "tenant.recentActions": "Recent admin actions",
  "tenant.recentActionsDescription": "Configuration and app lifecycle events.", "tenant.licenseEvents": "License events",
  "tenant.licenseEventsDescription": "License import, activation, and selection history.", "tenant.export": "Export", "tenant.exportDescription": "Tenant evidence bundle for audits and operations.",
  "tenant.noPrivileges": "No tenant privileges", "tenant.remove": "Remove",
  "platform.title": "Platform configuration", "platform.description": "Instance-wide controls for trust, app distribution, and platform governance.",
  "platform.trustedOrigins": "Trusted origins", "platform.users": "Users", "platform.tenants": "Tenants", "platform.feedExport": "Feed export",
  "platform.instanceState": "Instance state", "platform.instanceStateDescription": "Stable identifiers and platform-owned capabilities.", "platform.instance": "Instance",
  "platform.tenantMode": "Tenant mode", "platform.coreOwned": "Core-owned", "platform.deploymentPolicy": "Controlled by deployment policy",
  "platform.publishTokens": "Publish tokens", "platform.namespaceApproval": "Namespace and CI pre-approval", "platform.platformInstance": "Platform instance",
  "platform.platformInstanceDescription": "Public identity used by feeds, operators, and future trust metadata.", "platform.instanceName": "Instance name",
  "platform.publicBaseUrl": "Public base URL", "platform.saveInstance": "Save instance", "platform.trustedInstallOrigins": "Trusted install origins",
  "platform.originsDescription": "Exact-match origin allowlist (scheme, host and port) for manifest installation.", "platform.originsCount": "{{count}} origins",
  "platform.origin": "Origin", "platform.note": "Note", "platform.notePlaceholder": "Local inventory app", "platform.adding": "Adding...", "platform.addOrigin": "Add origin",
  "platform.allowHttp": "Allow HTTP for this origin (unsecured transport)", "platform.searchOrigins": "Search origins", "platform.loadingOrigins": "Loading trusted origins...",
  "platform.noOrigins": "No trusted origins.", "platform.noMatchingOrigins": "No matching origins.", "platform.created": "Created", "platform.actions": "Actions",
  "platform.distribution": "App distribution governance", "platform.distributionDescription": "Catalog feed import/export is managed in Applications. This area owns its platform policy.",
  "platform.partlyActive": "partly active", "platform.publicFeed": "Public feed", "platform.publicFeedDescription": "Only admin-published installed apps are exported.",
  "platform.publishRequests": "Publish requests", "platform.publishRequestsDescription": "User/developer proposals awaiting admin approval.",
  "platform.publishTokensDescription": "Admin-issued pre-approval for namespaces, apps, or CI pipelines.", "platform.roles": "Roles", "platform.userNotFound": "User not found.",
  "platform.usersDescription": "Platform identities. Open one user to edit profile fields or reset the password.", "platform.usersCount": "{{count}} users",
  "platform.addUser": "Add user", "platform.displayName": "Display name", "platform.initialPassword": "Initial password", "platform.createUser": "Create user", "platform.searchUsers": "Search users",
  "platform.tenantNotFound": "Tenant not found.", "platform.tenantsDescription": "Tenant records and their primary domains. Open one tenant to edit it.", "platform.tenantsCount": "{{count}} tenants",
  "platform.addTenant": "Add tenant", "platform.createTenant": "Create tenant", "platform.searchTenants": "Search tenants", "platform.rbacGrants": "RBAC grants",
  "platform.rbacDescription": "Assign platform-scoped and tenant-scoped privileges directly to users.", "platform.privilege": "Privilege", "platform.selectPrivilege": "Select privilege",
  "platform.scope": "Scope", "platform.allTenants": "Platform / all tenants", "platform.addGrant": "Add grant", "platform.action": "Action", "platform.noGrants": "Selected user has no grants.",
  "platform.automation": "Automation", "platform.automationDescription": "Scheduled feed sync and controlled runtime actions belong here.", "platform.trustedFeedRefresh": "Trusted feed refresh",
  "platform.trustedFeedRefreshDescription": "Opt-in refresh for verified and official catalog sources.", "platform.runtimeManager": "Compose runtime manager",
  "platform.runtimeManagerDescription": "Start, stop, update, and rotate credentials for managed app bundles.", "platform.policyAudit": "Policy audit",
  "platform.policyAuditDescription": "Automatic feed and runtime decisions are recorded in the audit log.", "platform.noUsers": "No users found.", "platform.identity": "Identity",
  "platform.userId": "User ID", "platform.grants": "Grants", "platform.status": "Status", "platform.backUsers": "Back to users", "platform.email": "Email",
  "platform.saveUser": "Save user", "platform.newPassword": "New password", "platform.passwordHint": "At least eight characters", "platform.resetPassword": "Reset password",
  "platform.createdGrants": "Created {{date}} · {{count}} privilege grants", "platform.noTenants": "No tenants found.", "platform.tenant": "Tenant", "platform.tenantId": "Tenant ID",
  "platform.primaryDomain": "Primary domain", "platform.backTenants": "Back to tenants", "platform.saveTenant": "Save tenant", "platform.createdUpdated": "Created {{created}} · Updated {{updated}}",
  "platform.customPrivilege": "Custom privilege", "platform.platform": "Platform", "platform.allTenantsLabel": "All tenants", "platform.remove": "Remove",
  "platform.noNote": "No note", "platform.edit": "Edit", "platform.delete": "Delete", "platform.saveNote": "Save note", "platform.deleteOrigin": "Delete this trusted origin?",
  "platform.confirmDelete": "Confirm delete", "platform.originRequired": "Origin is required.", "platform.httpConfirmation": "You must explicitly enable Allow HTTP for an http:// origin.",
  "platform.originAdded": "Trusted origin added.", "platform.instanceUpdated": "Platform instance settings were updated.", "platform.userCreated": "User was created.",
  "platform.tenantCreated": "Tenant was created.", "platform.platformPrivilegeScope": "Platform privilege cannot be scoped to a tenant.", "platform.grantExists": "This privilege grant already exists.",
  "platform.grantAdded": "Privilege grant was added.", "platform.grantRemoved": "Privilege grant was removed.",
} as const;

const cs: Record<keyof typeof en, string> = {
  ...en,
  "config.configuration": "Nastavení", "config.never": "Nikdy", "config.active": "aktivní", "config.disabled": "zakázáno",
  "authors.jwksRequired": "JWKS musí obsahovat alespoň jeden veřejný klíč.", "authors.title": "Autoři aplikací", "authors.authors": "Autoři",
  "authors.rootKeys": "Kořenové klíče", "authors.revocations": "Odvolání", "authors.trustSync": "Synchronizace důvěry", "authors.current": "Aktuální", "authors.missing": "Chybí",
  "authors.registryTrust": "Důvěra registru autorů", "authors.noTrustSnapshot": "Pro nastavený registr zatím nebyl synchronizován žádný snímek důvěry.",
  "authors.syncing": "Synchronizace...", "authors.syncTrust": "Synchronizovat důvěru", "authors.lastSynchronized": "Poslední synchronizace", "authors.synchronizedBy": "Synchronizoval",
  "authors.registry": "Registr", "authors.description": "Identity autorů z registru a jejich veřejné podpisové klíče.", "authors.count": "Autoři: {{count}}",
  "authors.onboardAuthor": "Přidat autora", "authors.displayName": "Zobrazovaný název", "authors.publicJwks": "Veřejný JWKS", "authors.certificateTtl": "Platnost certifikátu",
  "authors.onboarding": "Přidávání...", "authors.onboard": "Přidat", "authors.loading": "Načítání autorů...", "authors.rootKey": "Kořenový klíč",
  "authors.publicKeys": "Veřejné klíče", "authors.updated": "Aktualizováno", "authors.notReported": "Neuvedeno", "authors.replacementJwks": "Nový veřejný JWKS",
  "authors.rotating": "Obnova...", "authors.rotateKeys": "Obnovit klíče", "authors.none": "Nejsou přidáni žádní autoři.", "authors.author": "Autor", "authors.action": "Akce",
  "authors.onboarded": "Autor {{name}} byl přidán.", "authors.rotated": "Podpisové klíče autora {{name}} byly obnoveny.", "authors.synchronized": "Data důvěry registru autorů byla synchronizována.",
  "tenant.title": "Nastavení tenantu", "tenant.description": "Nastavení identity, přístupu k aplikacím a výběru licencí pro tenant.",
  "tenant.detailsUpdated": "Údaje tenantu byly aktualizovány.", "tenant.privilegeExists": "Uživatel již toto oprávnění tenantu má.",
  "tenant.privilegeAdded": "Oprávnění tenantu bylo přidáno.", "tenant.privilegeRemoved": "Oprávnění tenantu bylo odebráno.",
  "tenant.installedApps": "Nainstalované aplikace", "tenant.licenseRequired": "Vyžadují licenci", "tenant.users": "Uživatelé", "tenant.mode": "Režim tenantu",
  "tenant.fallbackName": "Tenant", "tenant.noPrimaryDomain": "Bez primární domény", "tenant.details": "Podrobnosti tenantu",
  "tenant.detailsDescription": "Upravte zobrazovaný název a primární doménu používanou k rozpoznání tenantu.", "tenant.name": "Název tenantu", "tenant.primaryDomain": "Primární doména",
  "tenant.save": "Uložit tenant", "tenant.dataPolicy": "Zásady dat", "tenant.dataPolicyDescription": "Shrnutí uchovávání a izolace dat tenantu.",
  "tenant.operationalContacts": "Provozní kontakty", "tenant.operationalContactsDescription": "Osoby a adresy odpovědné za provoz tenantu.",
  "tenant.usersRoles": "Uživatelé a oprávnění", "tenant.usersRolesDescription": "Správa přidělených oprávnění tenantu pro uživatele známé platformě.",
  "tenant.usersCount": "Uživatelé: {{count}}", "tenant.user": "Uživatel", "tenant.privilege": "Oprávnění tenantu", "tenant.selectPrivilege": "Vyberte oprávnění tenantu",
  "tenant.addPrivilege": "Přidat oprávnění", "tenant.noUsers": "Tenant zatím nemá uživatele. Správce platformy může vytvořit uživatele a udělit první oprávnění v Nastavení platformy.",
  "tenant.appsLicenses": "Aplikace a licence", "tenant.appsLicensesDescription": "Instalace aplikací, synchronizace katalogu, publikování feedu a výběr licencí se spravují v Aplikacích.",
  "tenant.activeElsewhere": "aktivní jinde", "tenant.installedAppsDescription": "Běhové aplikace známé této instanci Core.", "tenant.licenseApps": "Aplikace vyžadující licenci",
  "tenant.licenseAppsDescription": "Záznamy katalogu vyžadující výběr licence tenantu.", "tenant.feedPublishing": "Publikování feedu", "tenant.adminGated": "pouze správce",
  "tenant.feedPublishingDescription": "Do feedu této instance lze publikovat pouze nainstalované aplikace.", "tenant.auditContext": "Auditní kontext",
  "tenant.auditDescription": "Po zpřístupnění auditního API zde bude vyhledávání a kontrola auditu tenantu.", "tenant.recentActions": "Nedávné akce správců",
  "tenant.recentActionsDescription": "Události nastavení a životního cyklu aplikací.", "tenant.licenseEvents": "Licenční události",
  "tenant.licenseEventsDescription": "Historie importu, aktivace a výběru licencí.", "tenant.export": "Export", "tenant.exportDescription": "Balíček podkladů tenantu pro audit a provoz.",
  "tenant.noPrivileges": "Bez oprávnění tenantu", "tenant.remove": "Odebrat",
  "platform.title": "Nastavení platformy", "platform.description": "Nastavení důvěry, distribuce aplikací a správy celé instance.",
  "platform.trustedOrigins": "Důvěryhodné zdroje", "platform.users": "Uživatelé", "platform.tenants": "Tenanty", "platform.feedExport": "Export feedu",
  "platform.instanceState": "Stav instance", "platform.instanceStateDescription": "Stabilní identifikátory a možnosti vlastněné platformou.", "platform.instance": "Instance",
  "platform.tenantMode": "Režim tenantu", "platform.coreOwned": "Spravovaný Core", "platform.deploymentPolicy": "Řízeno zásadami nasazení",
  "platform.publishTokens": "Publikační tokeny", "platform.namespaceApproval": "Předběžné schválení namespace a CI", "platform.platformInstance": "Instance platformy",
  "platform.platformInstanceDescription": "Veřejná identita používaná feedy, správci a budoucími metadaty důvěry.", "platform.instanceName": "Název instance",
  "platform.publicBaseUrl": "Veřejná základní URL", "platform.saveInstance": "Uložit instanci", "platform.trustedInstallOrigins": "Důvěryhodné zdroje instalací",
  "platform.originsDescription": "Seznam přesně odpovídajících zdrojů (schéma, hostitel a port) povolených pro instalaci manifestů.", "platform.originsCount": "Zdroje: {{count}}",
  "platform.origin": "Zdroj", "platform.note": "Poznámka", "platform.notePlaceholder": "Místní inventární aplikace", "platform.adding": "Přidávání...", "platform.addOrigin": "Přidat zdroj",
  "platform.allowHttp": "Povolit HTTP pro tento zdroj (nezabezpečený přenos)", "platform.searchOrigins": "Prohledat zdroje", "platform.loadingOrigins": "Načítání důvěryhodných zdrojů...",
  "platform.noOrigins": "Žádné důvěryhodné zdroje.", "platform.noMatchingOrigins": "Žádné odpovídající zdroje.", "platform.created": "Vytvořeno", "platform.actions": "Akce",
  "platform.distribution": "Správa distribuce aplikací", "platform.distributionDescription": "Import a export katalogových feedů se spravuje v Aplikacích. Zde se nastavují zásady platformy.",
  "platform.partlyActive": "částečně aktivní", "platform.publicFeed": "Veřejný feed", "platform.publicFeedDescription": "Exportují se pouze správcem publikované nainstalované aplikace.",
  "platform.publishRequests": "Žádosti o publikování", "platform.publishRequestsDescription": "Návrhy uživatelů a vývojářů čekající na schválení správcem.",
  "platform.publishTokensDescription": "Správcem vydané předběžné schválení pro namespace, aplikace nebo CI.", "platform.roles": "Role", "platform.userNotFound": "Uživatel nebyl nalezen.",
  "platform.usersDescription": "Identity platformy. Otevřete uživatele pro úpravu profilu nebo reset hesla.", "platform.usersCount": "Uživatelé: {{count}}",
  "platform.addUser": "Přidat uživatele", "platform.displayName": "Zobrazované jméno", "platform.initialPassword": "Počáteční heslo", "platform.createUser": "Vytvořit uživatele", "platform.searchUsers": "Prohledat uživatele",
  "platform.tenantNotFound": "Tenant nebyl nalezen.", "platform.tenantsDescription": "Záznamy tenantů a jejich primární domény. Otevřete tenant pro úpravu.", "platform.tenantsCount": "Tenanty: {{count}}",
  "platform.addTenant": "Přidat tenant", "platform.createTenant": "Vytvořit tenant", "platform.searchTenants": "Prohledat tenanty", "platform.rbacGrants": "Přidělení RBAC",
  "platform.rbacDescription": "Přiřazení oprávnění platformy a tenantů přímo uživatelům.", "platform.privilege": "Oprávnění", "platform.selectPrivilege": "Vyberte oprávnění",
  "platform.scope": "Rozsah", "platform.allTenants": "Platforma / všechny tenanty", "platform.addGrant": "Přidat oprávnění", "platform.action": "Akce", "platform.noGrants": "Vybraný uživatel nemá žádná oprávnění.",
  "platform.automation": "Automatizace", "platform.automationDescription": "Plánovaná synchronizace feedů a řízené akce běhových prostředí.", "platform.trustedFeedRefresh": "Obnova důvěryhodných feedů",
  "platform.trustedFeedRefreshDescription": "Volitelná obnova ověřených a oficiálních katalogových zdrojů.", "platform.runtimeManager": "Správce Compose běhu",
  "platform.runtimeManagerDescription": "Spouštění, zastavení, aktualizace a obnova přihlašovacích údajů spravovaných balíčků.", "platform.policyAudit": "Audit zásad",
  "platform.policyAuditDescription": "Automatická rozhodnutí feedů a běhových prostředí se zapisují do auditu.", "platform.noUsers": "Nebyli nalezeni žádní uživatelé.", "platform.identity": "Identita",
  "platform.userId": "ID uživatele", "platform.grants": "Oprávnění", "platform.status": "Stav", "platform.backUsers": "Zpět na uživatele", "platform.email": "E-mail",
  "platform.saveUser": "Uložit uživatele", "platform.newPassword": "Nové heslo", "platform.passwordHint": "Alespoň osm znaků", "platform.resetPassword": "Resetovat heslo",
  "platform.createdGrants": "Vytvořeno {{date}} · Přidělená oprávnění: {{count}}", "platform.noTenants": "Nebyly nalezeny žádné tenanty.", "platform.tenant": "Tenant", "platform.tenantId": "ID tenantu",
  "platform.primaryDomain": "Primární doména", "platform.backTenants": "Zpět na tenanty", "platform.saveTenant": "Uložit tenant", "platform.createdUpdated": "Vytvořeno {{created}} · Aktualizováno {{updated}}",
  "platform.customPrivilege": "Vlastní oprávnění", "platform.platform": "Platforma", "platform.allTenantsLabel": "Všechny tenanty", "platform.remove": "Odebrat",
  "platform.noNote": "Bez poznámky", "platform.edit": "Upravit", "platform.delete": "Smazat", "platform.saveNote": "Uložit poznámku", "platform.deleteOrigin": "Smazat tento důvěryhodný zdroj?",
  "platform.confirmDelete": "Potvrdit smazání", "platform.originRequired": "Zdroj je povinný.", "platform.httpConfirmation": "Pro zdroj http:// musíte výslovně povolit HTTP.",
  "platform.originAdded": "Důvěryhodný zdroj byl přidán.", "platform.instanceUpdated": "Nastavení instance platformy bylo aktualizováno.", "platform.userCreated": "Uživatel byl vytvořen.",
  "platform.tenantCreated": "Tenant byl vytvořen.", "platform.platformPrivilegeScope": "Oprávnění platformy nelze omezit na tenant.", "platform.grantExists": "Toto přidělení oprávnění již existuje.",
  "platform.grantAdded": "Oprávnění bylo přidáno.", "platform.grantRemoved": "Oprávnění bylo odebráno.",
};

export const configResources = { en, cs };
