import { useState } from "react";
import { useLocalization } from "../../../../localization/LocalizationProvider";
import { Button } from "../../../../ui-kit/components/Button";
import { Card } from "../../../../ui-kit/components/Card";
import { EmptyState, PageHeader, SectionHeader, StatusBadge } from "../../../../ui-kit/components/Page";
import { Table } from "../../../../ui-kit/components/Table";
import { authorPortalRequests, useAuthorPortalMutation, useCatalogSubmissions } from "./api";

export function CatalogReviewPage() { const { t } = useLocalization(); const query = useCatalogSubmissions("registry", ""); const mutation = useAuthorPortalMutation(authorPortalRequests.reviewCatalog); const [notes] = useState(""); const act = (id: string, action: string) => mutation.mutate({ submissionId: id, action, notes }); return <div className="space-y-5"><PageHeader eyebrow={t("nav.platformSettings")} title={t("authorPortal.catalogSubmissions")} description={t("authorPortal.catalogDescription")} /><Card className="p-0"><SectionHeader title={t("authorPortal.catalogSubmissions")} />{query.data?.items.length ? <Table className="rounded-none border-x-0"><tbody>{query.data.items.map((item) => <tr key={item.submission_id}><td>{item.display_name ?? item.app_id}</td><td><StatusBadge>{t(`authorPortal.status.${item.status}`)}</StatusBadge></td><td className="flex gap-2">{item.status === "submitted" && <Button size="sm" onClick={() => act(item.submission_id, "start_review")}>{t("authorPortal.startReview")}</Button>}{item.status === "pending_review" && <><Button size="sm" onClick={() => act(item.submission_id, "approve")}>{t("authorPortal.approve")}</Button><Button size="sm" variant="danger" onClick={() => act(item.submission_id, "reject")}>{t("authorPortal.reject")}</Button></>}{item.status === "approved" && <Button size="sm" onClick={() => act(item.submission_id, "publish")}>{t("authorPortal.publish")}</Button>}{item.status === "published" && <Button size="sm" variant="danger" onClick={() => act(item.submission_id, "unpublish")}>{t("authorPortal.unpublish")}</Button>}</td></tr>)}</tbody></Table> : <EmptyState>{t("authorPortal.noCatalogSubmissions")}</EmptyState>}</Card></div>; }
