import { useEffect, useState } from "react";
import { Link, useLocation } from "react-router-dom";

import {
  authorPortalRequests,
  useAdminAuthorRequests,
  useAuthorActivity,
  useAuthorApps,
  useAuthorMembers,
  useAuthorOverview,
  useAuthorPortalMutation,
  useCatalogSubmissions,
  useGitConnections,
  useGitRepositories,
  type AuthorApp,
  type AuthorMode,
  type AuthorRequest,
  type AuthorProfile,
} from "../../data/api/author-portal";
import { readErrorMessage } from "../../data/api/read-error-message";
import { useLocalization } from "../../localization/LocalizationProvider";
import { Button } from "../../ui-kit/components/Button";
import { Card } from "../../ui-kit/components/Card";
import { Input } from "../../ui-kit/components/Input";
import { EmptyState, Field, MetricStrip, PageHeader, SectionHeader, StatusBadge } from "../../ui-kit/components/Page";
import { Select } from "../../ui-kit/components/Select";
import { Table } from "../../ui-kit/components/Table";
import { ToastNotice } from "../../ui-kit/components/ToastNotice";

const modes: AuthorMode[] = ["talpaversum_hosted", "trusted_self_hosted", "private_self_hosted"];
const tone = (status: string): "neutral" | "success" | "warning" | "danger" | "info" =>
  ["approved", "active", "ready_for_review", "running", "published"].includes(status) ? "success" :
    ["rejected", "revoked", "manifest_invalid", "disabled"].includes(status) ? "danger" :
      ["submitted", "pending_review", "needs_changes", "runtime_pending", "suspended"].includes(status) ? "warning" : "neutral";

type AuthorModule = "workspace" | "onboarding" | "registry";

export function AuthorPortalPage({ module = "workspace" }: { module?: AuthorModule }) {
  const { t } = useLocalization(); const location = useLocation(); const section = location.pathname.split("/")[3] ?? "";
  const overview = useAuthorOverview(); const profiles = overview.data?.profiles ?? [];
  const [activeAuthorId, setActiveAuthorId] = useState(() => localStorage.getItem("hc.activeAuthorId") ?? "");
  useEffect(() => { if (module !== "workspace" || !profiles.length) return; const valid = profiles.some((profile) => profile.author_id === activeAuthorId); if (!valid) { setActiveAuthorId(profiles[0].author_id); localStorage.setItem("hc.activeAuthorId", profiles[0].author_id); } }, [activeAuthorId, module, profiles]);
  const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const notify = async (action: () => Promise<unknown>, success: string) => { setError(null); try { await action(); setMessage(success); } catch (err) { setError(readErrorMessage(err)); } };
  const instance = overview.data?.capabilities.instance;
  const available = module === "onboarding" ? instance?.officialAuthorOnboarding.available : module === "registry" ? instance?.officialAuthorRegistry.available : true;
  const title = module === "registry" ? t("authorPortal.authorReviews") : module === "onboarding" ? t("authorPortal.become") : t("authorPortal.title"); const description = t("authorPortal.description");
  const header = <PageHeader eyebrow={t("authorPortal.eyebrow")} title={title} description={description} />;
  const toast = <ToastNotice message={error ?? message} tone={error ? "danger" : "success"} onDismiss={() => { setMessage(null); setError(null); }} />;

  let body;
  if (overview.isLoading) body = <Card><EmptyState>{t("common.loading")}</EmptyState></Card>;
  else if (!available) body = <Card><EmptyState>{t("authorPortal.capabilityUnavailable")}</EmptyState></Card>;
  else if (module === "onboarding") body = <BecomeAuthor profiles={profiles} requests={overview.data?.requests ?? []} notify={notify} />;
  else if (module === "registry" && section === "catalog") body = <Catalog registry notify={notify} />;
  else if (module === "registry" && section === "applications") body = <Applications registry catalogOperator={Boolean(overview.data?.capabilities.catalog_review)} runtimeOperator={Boolean(overview.data?.capabilities.runtime_review)} notify={notify} />;
  else if (module === "registry") body = <Reviews enabled={Boolean(overview.data?.capabilities.author_review)} notify={notify} />;
  else if (section === "profiles") body = <Profiles profiles={profiles} notify={notify} />;
  else if (section === "git") body = <GitConnections profiles={profiles} notify={notify} />;
  else if (section === "applications") body = <Applications catalogOperator={Boolean(overview.data?.capabilities.catalog_review)} runtimeOperator={Boolean(overview.data?.capabilities.runtime_review)} notify={notify} />;
  else if (section === "licensing") body = <AuthorLicensing profiles={profiles} />;
  else if (section === "catalog") body = <Catalog notify={notify} />;
  else if (section === "activity") body = <Activity />;
  else body = <Overview data={overview.data} />;

  return <div className="space-y-5">{header}{module === "workspace" && profiles.length > 0 && <Card><Field label={t("authorPortal.activeAuthor")} hint={activeAuthorId}><Select value={activeAuthorId} onChange={(event) => { setActiveAuthorId(event.target.value); localStorage.setItem("hc.activeAuthorId", event.target.value); }}>{profiles.map((profile) => <option key={profile.author_id} value={profile.author_id}>{profile.display_name} ({profile.author_id})</option>)}</Select></Field></Card>}{toast}{body}</div>;
}

function Overview({ data }: { data: ReturnType<typeof useAuthorOverview>["data"] }) {
  const { t } = useLocalization();
  return <>
    <MetricStrip items={[{ label: t("authorPortal.requests"), value: data?.requests.length ?? 0 }, { label: t("authorPortal.profiles"), value: data?.profiles.length ?? 0 }, { label: t("authorPortal.applications"), value: data?.apps.length ?? 0 }, { label: t("authorPortal.catalogSubmissions"), value: data?.submissions.length ?? 0 }]} />
    <div className="grid gap-3 lg:grid-cols-3">{modes.map((mode) => <Card key={mode} className="space-y-3"><div className="flex items-center justify-between gap-2"><h2 className="text-sm font-semibold">{t(`authorPortal.mode.${mode}`)}</h2><StatusBadge tone={mode === "private_self_hosted" ? "neutral" : "info"}>{mode === "private_self_hosted" ? t("authorPortal.private") : t("authorPortal.official")}</StatusBadge></div><p className="text-sm text-hc-muted">{t(`authorPortal.mode.${mode}.description`)}</p><div className="text-xs text-hc-muted">{t(`authorPortal.mode.${mode}.responsibility`)}</div></Card>)}</div>
    {!data?.profiles.length && <Card><EmptyState><div className="space-y-3"><p>{t("authorPortal.emptyOverview")}</p>{data?.capabilities.instance.officialAuthorOnboarding.available && <Link className="text-hc-primary" to="/core/author-onboarding">{t("authorPortal.become")}</Link>}</div></EmptyState></Card>}
  </>;
}

function BecomeAuthor({ requests, notify }: { profiles: unknown[]; requests: AuthorRequest[]; notify: (action: () => Promise<unknown>, success: string) => Promise<void> }) {
  const { t } = useLocalization(); const [editingId, setEditingId] = useState<string | null>(null); const [mode, setMode] = useState<AuthorMode>("talpaversum_hosted"); const [name, setName] = useState(""); const [legal, setLegal] = useState(""); const [email, setEmail] = useState(""); const [website, setWebsite] = useState(""); const [gitProfile, setGitProfile] = useState(""); const [description, setDescription] = useState(""); const [distribution, setDistribution] = useState("official_catalog"); const [terms, setTerms] = useState(false); const [jwks, setJwks] = useState(""); const [issuerUrl, setIssuerUrl] = useState("");
  const create = useAuthorPortalMutation(authorPortalRequests.createRequest); const update = useAuthorPortalMutation(authorPortalRequests.updateRequest); const submit = useAuthorPortalMutation(authorPortalRequests.submitRequest);
  const values = () => { let publicJwks = null; if (mode === "trusted_self_hosted") publicJwks = JSON.parse(jwks); return { requested_display_name: name, legal_name: legal || null, contact_email: email, website: website || null, git_provider_profile: gitProfile || null, description, operating_mode: mode, intended_distribution: distribution, terms_accepted: terms, public_jwks: publicJwks, external_issuer_url: issuerUrl || null }; };
  const save = () => notify(async () => { if (editingId) await update.mutateAsync({ requestId: editingId, values: values() }); else await create.mutateAsync(values()); }, t(editingId ? "authorPortal.requestUpdated" : "authorPortal.requestSaved"));
  const edit = (item: AuthorRequest) => { setEditingId(item.request_id); setMode(item.operating_mode); setName(item.requested_display_name); setLegal(item.legal_name ?? ""); setEmail(item.contact_email); setWebsite(item.website ?? ""); setGitProfile(item.git_provider_profile ?? ""); setDescription(item.description); setDistribution(item.intended_distribution); setTerms(item.terms_accepted); setJwks(item.public_jwks_json ? JSON.stringify(item.public_jwks_json, null, 2) : ""); setIssuerUrl(item.external_issuer_url ?? ""); };
  return <div className="space-y-4">
    <Card className="space-y-4"><SectionHeader className="-mx-4 -mt-4" title={t("authorPortal.become")} description={t("authorPortal.becomeDescription")} />
      <div className="grid gap-3 lg:grid-cols-3">{modes.map((item) => <button type="button" key={item} onClick={() => setMode(item)} className={`rounded-hc-md border p-3 text-left ${mode === item ? "border-hc-primary bg-hc-primary/10" : "border-hc-outline"}`}><div className="text-sm font-semibold">{t(`authorPortal.mode.${item}`)}</div><div className="mt-1 text-xs text-hc-muted">{t(`authorPortal.mode.${item}.description`)}</div></button>)}</div>
      {mode === "private_self_hosted" ? <div className="rounded-hc-md border border-hc-outline bg-hc-surface-variant p-4 text-sm"><p>{t("authorPortal.privateGuidance")}</p><div className="mt-3 flex gap-3"><Link className="text-hc-primary" to="/core/platform/trusted-origins">{t("authorPortal.configureOrigins")}</Link><Link className="text-hc-primary" to="/core/apps">{t("authorPortal.installPrivateApp")}</Link></div></div> : <>
        <div className="grid gap-3 md:grid-cols-2"><Field label={t("authorPortal.displayName")}><Input value={name} onChange={(e) => setName(e.target.value)} /></Field><Field label={t("authorPortal.legalName")}><Input value={legal} onChange={(e) => setLegal(e.target.value)} /></Field><Field label={t("authorPortal.contactEmail")}><Input type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></Field><Field label={t("authorPortal.website")}><Input value={website} onChange={(e) => setWebsite(e.target.value)} /></Field><Field label={t("authorPortal.gitProfile")}><Input value={gitProfile} onChange={(e) => setGitProfile(e.target.value)} /></Field><Field label={t("authorPortal.distribution")}><Select value={distribution} onChange={(e) => setDistribution(e.target.value)}><option value="official_catalog">{t("authorPortal.distribution.official")}</option><option value="private_catalog">{t("authorPortal.distribution.private")}</option><option value="manual">{t("authorPortal.distribution.manual")}</option></Select></Field></div>
        <Field label={t("authorPortal.descriptionLabel")}><textarea className="min-h-24 rounded-hc-md border border-hc-outline bg-hc-bg px-3 py-2 text-sm" value={description} onChange={(e) => setDescription(e.target.value)} /></Field>
        {mode === "trusted_self_hosted" && <div className="grid gap-3 md:grid-cols-2"><Field label={t("authorPortal.publicJwks")} hint={t("authorPortal.publicJwksHint")}><textarea className="min-h-28 rounded-hc-md border border-hc-outline bg-hc-bg px-3 py-2 font-mono text-xs" value={jwks} onChange={(e) => setJwks(e.target.value)} /></Field><Field label={t("authorPortal.externalIssuer")}><Input value={issuerUrl} onChange={(e) => setIssuerUrl(e.target.value)} /></Field></div>}
        <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={terms} onChange={(e) => setTerms(e.target.checked)} />{t("authorPortal.acceptTerms")}</label><div className="flex gap-2"><Button onClick={() => void save()} disabled={create.isPending || update.isPending}>{t(editingId ? "authorPortal.updateDraft" : "authorPortal.saveDraft")}</Button>{editingId && <Button variant="outlined" onClick={() => setEditingId(null)}>{t("authorPortal.cancelEdit")}</Button>}</div>
      </>}
    </Card>
    <Card className="p-0"><SectionHeader title={t("authorPortal.myRequests")} />{requests.length ? <Table className="rounded-none border-x-0 border-b-0"><thead><tr><th>{t("authorPortal.displayName")}</th><th>{t("authorPortal.mode")}</th><th>{t("authorPortal.status")}</th><th>{t("authorPortal.actions")}</th></tr></thead><tbody>{requests.map((item) => <tr key={item.request_id}><td>{item.requested_display_name}</td><td>{t(`authorPortal.mode.${item.operating_mode}`)}</td><td><StatusBadge tone={tone(item.status)}>{t(`authorPortal.status.${item.status}`)}</StatusBadge></td><td><div className="flex gap-2">{["draft", "needs_changes", "rejected"].includes(item.status) && <Button size="sm" variant="outlined" onClick={() => edit(item)}>{t("authorPortal.edit")}</Button>}{["draft", "needs_changes"].includes(item.status) && item.operating_mode !== "private_self_hosted" && <Button size="sm" onClick={() => void notify(() => submit.mutateAsync(item.request_id), t("authorPortal.requestSubmitted"))}>{t("authorPortal.submit")}</Button>}</div></td></tr>)}</tbody></Table> : <EmptyState>{t("authorPortal.noRequests")}</EmptyState>}</Card>
  </div>;
}

function Profiles({ profiles, notify }: { profiles: AuthorProfile[]; notify: (action: () => Promise<unknown>, success: string) => Promise<void> }) {
  const { t } = useLocalization(); const [selected, setSelected] = useState(profiles[0]?.author_id ?? ""); const [userId, setUserId] = useState(""); const [role, setRole] = useState("developer"); const members = useAuthorMembers(selected); const save = useAuthorPortalMutation(authorPortalRequests.saveMember);
  if (!profiles.length) return <Card><EmptyState>{t("authorPortal.noProfiles")}</EmptyState></Card>;
  return <div className="space-y-4"><Card><Field label={t("authorPortal.profile")}><Select value={selected} onChange={(e) => setSelected(e.target.value)}>{profiles.map((p) => <option key={p.author_id} value={p.author_id}>{p.display_name}</option>)}</Select></Field></Card><Card className="p-0"><SectionHeader title={t("authorPortal.members")} description={t("authorPortal.membersDescription")} />{members.data?.items.length ? <Table className="rounded-none border-x-0"><thead><tr><th>{t("authorPortal.user")}</th><th>{t("authorPortal.role")}</th><th>{t("authorPortal.status")}</th></tr></thead><tbody>{members.data.items.map((m) => <tr key={m.user_id}><td>{m.email}<div className="text-xs text-hc-muted">{m.user_id}</div></td><td>{t(`authorPortal.role.${m.role}`)}</td><td>{t(`authorPortal.status.${m.status}`)}</td></tr>)}</tbody></Table> : <EmptyState>{t("authorPortal.noMembers")}</EmptyState>}<div className="grid gap-3 border-t border-hc-outline p-4 md:grid-cols-[1fr_14rem_auto]"><Input placeholder={t("authorPortal.userId")} value={userId} onChange={(e) => setUserId(e.target.value)} /><Select value={role} onChange={(e) => setRole(e.target.value)}>{["owner", "manager", "developer", "licensing", "viewer"].map((r) => <option key={r} value={r}>{t(`authorPortal.role.${r}`)}</option>)}</Select><Button onClick={() => void notify(() => save.mutateAsync({ authorId: selected, user_id: userId, role }), t("authorPortal.memberSaved"))}>{t("authorPortal.addMember")}</Button></div></Card></div>;
}

function GitConnections({ profiles, notify }: { profiles: Array<{ author_id: string; display_name: string }>; notify: (action: () => Promise<unknown>, success: string) => Promise<void> }) {
  const { t } = useLocalization(); const connections = useGitConnections(); const [authorId, setAuthorId] = useState(profiles[0]?.author_id ?? ""); const [token, setToken] = useState(""); const [connectionId, setConnectionId] = useState(""); const [repository, setRepository] = useState(""); const [branch, setBranch] = useState("main"); const [manifestPath, setManifestPath] = useState("manifest/app-manifest.json"); const [inspection, setInspection] = useState<{ errors: string[]; status: string } | null>(null); const repos = useGitRepositories(connectionId); const connect = useAuthorPortalMutation(authorPortalRequests.connectGitHub); const disconnect = useAuthorPortalMutation(authorPortalRequests.disconnectGit); const inspect = useAuthorPortalMutation(authorPortalRequests.inspectRepository); const create = useAuthorPortalMutation(authorPortalRequests.createApp);
  const selectedRepo = repos.data?.items.find((item) => item.full_name === repository); const selectRepo = (value: string) => { setRepository(value); const found = repos.data?.items.find((item) => item.full_name === value); if (found) setBranch(found.default_branch); };
  return <div className="space-y-4"><Card className="space-y-3"><SectionHeader className="-mx-4 -mt-4" title={t("authorPortal.connectGitHub")} description={t("authorPortal.gitSecurityHelp")} /><div className="grid gap-3 md:grid-cols-[1fr_2fr_auto]"><Select value={authorId} onChange={(e) => setAuthorId(e.target.value)}><option value="">{t("authorPortal.selectProfile")}</option>{profiles.map((p) => <option key={p.author_id} value={p.author_id}>{p.display_name}</option>)}</Select><Input type="password" placeholder={t("authorPortal.githubToken")} value={token} onChange={(e) => setToken(e.target.value)} /><Button onClick={() => void notify(async () => { await connect.mutateAsync({ author_id: authorId, token }); setToken(""); }, t("authorPortal.gitConnected"))}>{t("authorPortal.connect")}</Button></div></Card>
    <Card className="p-0"><SectionHeader title={t("authorPortal.gitConnections")} />{connections.data?.items.length ? <Table className="rounded-none border-x-0"><thead><tr><th>{t("authorPortal.account")}</th><th>{t("authorPortal.status")}</th><th>{t("authorPortal.actions")}</th></tr></thead><tbody>{connections.data.items.map((c) => <tr key={c.connection_id}><td>{c.provider}: {c.account_login}</td><td><StatusBadge tone={tone(c.status)}>{t(`authorPortal.status.${c.status}`)}</StatusBadge></td><td className="flex gap-2"><Button size="sm" variant="outlined" onClick={() => setConnectionId(c.connection_id)}>{t("authorPortal.repositories")}</Button><Button size="sm" variant="danger" onClick={() => void notify(() => disconnect.mutateAsync(c.connection_id), t("authorPortal.gitDisconnected"))}>{t("authorPortal.disconnect")}</Button></td></tr>)}</tbody></Table> : <EmptyState>{t("authorPortal.noGitConnections")}</EmptyState>}</Card>
    {connectionId && <Card className="space-y-3"><SectionHeader className="-mx-4 -mt-4" title={t("authorPortal.createFromRepository")} description={t("authorPortal.privateRepoHelp")} /><div className="grid gap-3 md:grid-cols-3"><Field label={t("authorPortal.repository")}><Select value={repository} onChange={(e) => selectRepo(e.target.value)}><option value="">{t("authorPortal.selectRepository")}</option>{repos.data?.items.map((repo) => <option key={repo.id} value={repo.full_name}>{repo.full_name} ({t(`authorPortal.repository.${repo.visibility}`)})</option>)}</Select></Field><Field label={t("authorPortal.branch")}><Input value={branch} onChange={(e) => setBranch(e.target.value)} /></Field><Field label={t("authorPortal.manifestPath")}><Input value={manifestPath} onChange={(e) => setManifestPath(e.target.value)} /></Field></div>{selectedRepo && <StatusBadge tone={selectedRepo.visibility === "private" ? "warning" : "info"}>{t(`authorPortal.repository.${selectedRepo.visibility}`)}</StatusBadge>}<div className="flex gap-2"><Button variant="outlined" onClick={() => void notify(async () => { const result = await inspect.mutateAsync({ connection_id: connectionId, repository, branch, manifest_path: manifestPath }) as { errors: string[]; status: string }; setInspection(result); }, t("authorPortal.manifestChecked"))}>{t("authorPortal.validateManifest")}</Button><Button disabled={Boolean(inspection?.errors.length)} onClick={() => void notify(() => create.mutateAsync({ author_id: authorId, connection_id: connectionId, repository, branch, manifest_path: manifestPath }), t("authorPortal.appDraftCreated"))}>{t("authorPortal.createApp")}</Button></div>{inspection && <div className={`rounded-hc-md border p-3 text-sm ${inspection.errors.length ? "border-hc-danger text-hc-danger" : "border-hc-success text-hc-success"}`}>{inspection.errors.length ? inspection.errors.join("; ") : t("authorPortal.manifestValid")}</div>}</Card>}
  </div>;
}

function Applications({ catalogOperator, runtimeOperator, notify, registry = false }: { catalogOperator: boolean; runtimeOperator: boolean; registry?: boolean; notify: (action: () => Promise<unknown>, success: string) => Promise<void> }) {
  const { t } = useLocalization(); const apps = useAuthorApps(registry ? "registry" : "workspace"); const action = useAuthorPortalMutation(authorPortalRequests.appAction); const catalog = useAuthorPortalMutation(authorPortalRequests.submitCatalog);
  const buttons = (app: AuthorApp) => { const canSubmit = app.member_permissions_json?.includes("author.apps.submit"); const canPublish = app.member_permissions_json?.includes("author.apps.publish"); return <div className="flex flex-wrap gap-2">{canSubmit && app.status === "ready_for_review" && <Button size="sm" onClick={() => void notify(() => action.mutateAsync({ appId: app.author_app_id, action: "submit" }), t("authorPortal.appSubmitted"))}>{t("authorPortal.submit")}</Button>}{catalogOperator && app.status === "submitted" && <><Button size="sm" onClick={() => void notify(() => action.mutateAsync({ appId: app.author_app_id, action: "approve" }), t("authorPortal.appApproved"))}>{t("authorPortal.approve")}</Button><Button size="sm" variant="danger" onClick={() => void notify(() => action.mutateAsync({ appId: app.author_app_id, action: "reject" }), t("authorPortal.appRejected"))}>{t("authorPortal.reject")}</Button></>}{canSubmit && app.status === "approved" && app.runtime_management === "talpaversum_managed" && <Button size="sm" onClick={() => void notify(() => action.mutateAsync({ appId: app.author_app_id, action: "request_runtime" }), t("authorPortal.runtimeRequested"))}>{t("authorPortal.requestRuntime")}</Button>}{runtimeOperator && app.status === "runtime_pending" && <Button size="sm" onClick={() => void notify(() => action.mutateAsync({ appId: app.author_app_id, action: "approve_runtime" }), t("authorPortal.runtimeApproved"))}>{t("authorPortal.approveRuntime")}</Button>}{canPublish && ["approved", "running", "runtime_approved"].includes(app.status) && <Button size="sm" variant="outlined" onClick={() => void notify(() => catalog.mutateAsync(app.author_app_id), t("authorPortal.catalogSubmitted"))}>{t("authorPortal.submitCatalog")}</Button>}</div>; };
  return <Card className="p-0"><SectionHeader title={t("authorPortal.applications")} description={t("authorPortal.applicationsDescription")} />{apps.data?.items.length ? <Table className="rounded-none border-x-0 border-b-0"><thead><tr><th>{t("authorPortal.application")}</th><th>{t("authorPortal.source")}</th><th>{t("authorPortal.runtime")}</th><th>{t("authorPortal.status")}</th><th>{t("authorPortal.actions")}</th></tr></thead><tbody>{apps.data.items.map((app) => <tr key={app.author_app_id}><td>{app.display_name}<div className="text-xs text-hc-muted">{app.app_id ?? app.author_app_id}</div></td><td>{app.repository_full_name}<div className="text-xs text-hc-muted">{app.branch} · {app.manifest_path}</div>{app.manifest_json && <details className="mt-2 max-w-md"><summary className="cursor-pointer text-xs text-hc-primary">{t("authorPortal.reviewRuntimePlan")}</summary><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap rounded-hc-sm bg-hc-bg p-2 text-xs text-hc-muted">{JSON.stringify({ deployment: app.manifest_json.deployment, runtime: app.manifest_json.runtime, integration: app.manifest_json.integration, privileges: app.manifest_json.privileges }, null, 2)}</pre></details>}</td><td>{t(`authorPortal.runtime.${app.runtime_management}`)}</td><td><StatusBadge tone={tone(app.status)}>{t(`authorPortal.status.${app.status}`)}</StatusBadge>{app.manifest_errors_json?.length > 0 && <div className="mt-1 max-w-xs text-xs text-hc-danger">{app.manifest_errors_json.join("; ")}</div>}</td><td>{buttons(app)}</td></tr>)}</tbody></Table> : <EmptyState>{t("authorPortal.noApplications")}</EmptyState>}</Card>;
}

function AuthorLicensing({ profiles }: { profiles: Array<{ author_id: string; display_name: string; operating_mode: AuthorMode; external_issuer_url?: string | null }> }) {
  const { t } = useLocalization(); return <div className="grid gap-3 lg:grid-cols-2">{profiles.length ? profiles.map((profile) => <Card key={profile.author_id} className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">{profile.display_name}</h2><StatusBadge>{t(`authorPortal.mode.${profile.operating_mode}`)}</StatusBadge></div><p className="text-sm text-hc-muted">{t(`authorPortal.licensing.${profile.operating_mode}`)}</p>{profile.operating_mode === "talpaversum_hosted" ? <Link className="text-sm text-hc-primary" to="/core/licensing">{t("authorPortal.openLicensing")}</Link> : profile.operating_mode === "trusted_self_hosted" ? <div className="text-xs text-hc-muted">{profile.external_issuer_url ?? t("authorPortal.issuerNotConfigured")}</div> : <Link className="text-sm text-hc-primary" to="/core/apps">{t("authorPortal.privateLicensing")}</Link>}</Card>) : <Card><EmptyState>{t("authorPortal.noProfiles")}</EmptyState></Card>}</div>;
}

function Catalog({ notify, registry = false }: { registry?: boolean; notify: (action: () => Promise<unknown>, success: string) => Promise<void> }) {
  const { t } = useLocalization(); const submissions = useCatalogSubmissions(registry ? "registry" : "workspace"); const review = useAuthorPortalMutation(authorPortalRequests.reviewCatalog);
  const actions = (item: NonNullable<typeof submissions.data>["items"][number]) => !submissions.data?.operator ? null : <div className="flex flex-wrap gap-2">{item.status === "submitted" && <Button size="sm" onClick={() => void notify(() => review.mutateAsync({ submissionId: item.submission_id, action: "start_review" }), t("authorPortal.reviewStarted"))}>{t("authorPortal.startReview")}</Button>}{item.status === "pending_review" && <><Button size="sm" onClick={() => void notify(() => review.mutateAsync({ submissionId: item.submission_id, action: "approve" }), t("authorPortal.catalogApproved"))}>{t("authorPortal.approve")}</Button><Button size="sm" variant="outlined" onClick={() => void notify(() => review.mutateAsync({ submissionId: item.submission_id, action: "request_changes" }), t("authorPortal.changesRequested"))}>{t("authorPortal.requestChanges")}</Button><Button size="sm" variant="danger" onClick={() => void notify(() => review.mutateAsync({ submissionId: item.submission_id, action: "reject" }), t("authorPortal.catalogRejected"))}>{t("authorPortal.reject")}</Button></>}{item.status === "approved" && <Button size="sm" onClick={() => void notify(() => review.mutateAsync({ submissionId: item.submission_id, action: "publish" }), t("authorPortal.catalogPublished"))}>{t("authorPortal.publish")}</Button>}{item.status === "published" && <Button size="sm" variant="danger" onClick={() => void notify(() => review.mutateAsync({ submissionId: item.submission_id, action: "unpublish" }), t("authorPortal.catalogUnpublished"))}>{t("authorPortal.unpublish")}</Button>}</div>;
  return <Card className="p-0"><SectionHeader title={t("authorPortal.catalogSubmissions")} description={t("authorPortal.catalogDescription")} />{submissions.data?.items.length ? <Table className="rounded-none border-x-0 border-b-0"><thead><tr><th>{t("authorPortal.application")}</th><th>{t("authorPortal.mode")}</th><th>{t("authorPortal.status")}</th><th>{t("authorPortal.actions")}</th></tr></thead><tbody>{submissions.data.items.map((item) => <tr key={item.submission_id}><td>{item.display_name ?? item.app_id ?? item.author_app_id}</td><td>{item.operating_mode ? t(`authorPortal.mode.${item.operating_mode}`) : "-"}</td><td><StatusBadge tone={tone(item.status)}>{t(`authorPortal.status.${item.status}`)}</StatusBadge></td><td>{actions(item)}</td></tr>)}</tbody></Table> : <EmptyState>{t("authorPortal.noCatalogSubmissions")}</EmptyState>}</Card>;
}

function Activity() { const { t } = useLocalization(); const activity = useAuthorActivity(); return <Card className="p-0"><SectionHeader title={t("authorPortal.activity")} description={t("authorPortal.activityDescription")} />{activity.data?.items.length ? <Table className="rounded-none border-x-0 border-b-0"><thead><tr><th>{t("authorPortal.event")}</th><th>{t("authorPortal.transition")}</th><th>{t("authorPortal.created")}</th></tr></thead><tbody>{activity.data.items.map((item) => <tr key={item.event_id}><td>{t(`authorPortal.event.${item.action}`)}</td><td>{item.from_status ? t(`authorPortal.status.${item.from_status}`) : "-"} → {item.to_status ? t(`authorPortal.status.${item.to_status}`) : "-"}</td><td>{new Date(item.created_at).toLocaleString()}</td></tr>)}</tbody></Table> : <EmptyState>{t("authorPortal.noActivity")}</EmptyState>}</Card>; }

function Reviews({ enabled, notify }: { enabled: boolean; notify: (action: () => Promise<unknown>, success: string) => Promise<void> }) {
  const { t } = useLocalization(); const requests = useAdminAuthorRequests(enabled); const review = useAuthorPortalMutation(authorPortalRequests.reviewRequest); const [notes, setNotes] = useState("");
  const actions = (item: AuthorRequest) => <div className="flex flex-wrap gap-2">{item.status === "submitted" && <Button size="sm" onClick={() => void notify(() => review.mutateAsync({ requestId: item.request_id, action: "start_review", notes }), t("authorPortal.reviewStarted"))}>{t("authorPortal.startReview")}</Button>}{item.status === "pending_review" && <><Button size="sm" onClick={() => void notify(() => review.mutateAsync({ requestId: item.request_id, action: "approve", notes }), t("authorPortal.authorApproved"))}>{t("authorPortal.approve")}</Button><Button size="sm" variant="outlined" onClick={() => void notify(() => review.mutateAsync({ requestId: item.request_id, action: "request_changes", notes }), t("authorPortal.changesRequested"))}>{t("authorPortal.requestChanges")}</Button><Button size="sm" variant="danger" onClick={() => void notify(() => review.mutateAsync({ requestId: item.request_id, action: "reject", notes }), t("authorPortal.authorRejected"))}>{t("authorPortal.reject")}</Button></>}{item.status === "approved" && <><Button size="sm" variant="outlined" onClick={() => void notify(() => review.mutateAsync({ requestId: item.request_id, action: "suspend", notes }), t("authorPortal.authorSuspended"))}>{t("authorPortal.suspend")}</Button><Button size="sm" variant="danger" onClick={() => void notify(() => review.mutateAsync({ requestId: item.request_id, action: "revoke", notes }), t("authorPortal.authorRevoked"))}>{t("authorPortal.revoke")}</Button></>}</div>;
  if (!enabled) return <Card><EmptyState>{t("authorPortal.operatorOnly")}</EmptyState></Card>;
  return <div className="space-y-4"><Card><Field label={t("authorPortal.reviewNotes")}><Input value={notes} onChange={(e) => setNotes(e.target.value)} /></Field></Card><Card className="p-0"><SectionHeader title={t("authorPortal.authorReviews")} description={t("authorPortal.reviewDescription")} />{requests.data?.items.length ? <Table className="rounded-none border-x-0 border-b-0"><thead><tr><th>{t("authorPortal.displayName")}</th><th>{t("authorPortal.mode")}</th><th>{t("authorPortal.status")}</th><th>{t("authorPortal.actions")}</th></tr></thead><tbody>{requests.data.items.map((item) => <tr key={item.request_id}><td>{item.requested_display_name}<div className="text-xs text-hc-muted">{item.contact_email}</div></td><td>{t(`authorPortal.mode.${item.operating_mode}`)}</td><td><StatusBadge tone={tone(item.status)}>{t(`authorPortal.status.${item.status}`)}</StatusBadge></td><td>{actions(item)}</td></tr>)}</tbody></Table> : <EmptyState>{t("authorPortal.noReviews")}</EmptyState>}</Card></div>;
}
